SotMSteamMods/CauldronMods

- CauldronMods.csproj
- Testing/BaseTest.cs
- Testing/Setup.cs
There are the changes I had to make to get the tests running directly in VS2019
> VS2019 support

- CauldronMods.csproj
Remove old reference to CodingBugs.txt location
Exclude sample CardController.cs from project file
> Exclude template sample

- Controller/Heroes/DocHavoc/Cards/BrawlerCardController.cs
- Controller/Heroes/DocHavoc/Cards/CauterizeCardController.cs
- Controller/Heroes/DocHavoc/Cards/FieldDressingCardController.cs
- Controller/Heroes/DocHavoc/Cards/GasMaskCardController.cs
- Controller/Heroes/DocHavoc/Cards/ImmediateEvacCardController.cs
- Controller/Heroes/DocHavoc/Cards/ImprovisedMineCardController.cs
- Controller/Heroes/DocHavoc/Cards/PainkillersCardController.cs
- Controller/Heroes/DocHavoc/Cards/PhosphorBlastCardController.cs
- Controller/Heroes/DocHavoc/Cards/RapidRegenCardController.cs
- Controller/Heroes/DocHavoc/Cards/RecklessChargeCardController.cs
- Controller/Heroes/DocHavoc/Cards/SearchAndRescueCardController.cs
- Controller/Heroes/DocHavoc/Cards/StimShotCardController.cs
- Controller/Heroes/DocHavoc/Cards/SyringeDartsCardController.cs
- Controller/Heroes/DocHavoc/Cards/UnstableSerumCardController.cs
- Controller/Heroes/DocHavoc/CharacterCards/DocHavocCharacterCardController.cs
- Testing/Heroes/DocHavocTests.cs
- Implement innate power and incaps with tests
- Stub remainder of cards
> Doc havoc innate incap

- Controller/Environments/TheWanderingIsle/Cards/TimedDetonatorCardController.cs
- Controller/Heroes/TheStranger/Cards/MarkOfTheBloodThornCardController.cs
- Controller/Heroes/TheStranger/CharacterCards/TheStrangerCharacterCardController.cs
- Testing/Heroes/TheStrangerTests.cs
> TheStrangerCharacterCard Power + Incaps

- Controller/Heroes/Necro/Cards/AbominationCardController.cs
- Controller/Heroes/Necro/Cards/BackfireHexCardController.cs
- Controller/Heroes/Necro/Cards/BloodRiteCardController.cs
- Controller/Heroes/Necro/Cards/BookOfTheDeadCardController.cs
- Controller/Heroes/Necro/Cards/ChaoticSummonCardController.cs
- Controller/Heroes/Necro/Cards/CorpseExplosionCardController.cs
- Controller/Heroes/Necro/Cards/DarkPactCardController.cs
- Controller/Heroes/Necro/Cards/DemonicImpCardController.cs
- Controller/Heroes/Necro/Cards/FinalRitualCardController.cs
- Controller/Heroes/Necro/Cards/GhoulCardController.cs
- Controller/Heroes/Necro/Cards/GrandSummonCardController.cs
- Controller/Heroes/Necro/Cards/HellfireCardController.cs
- Controller/Heroes/Necro/Cards/NecroZombieCardController.cs
- Controller/Heroes/Necro/Cards/PossessedCorpseCardController.cs
- Controller/Heroes/Necro/Cards/TaintedBloodCardController.cs
- Controller/Heroes/Necro/Cards/TalismanCardController.cs
- Controller/Heroes/Necro/CharacterCards/NecroCardController.cs
- Controller/Heroes/Necro/CharacterCards/NecroCharacterCardController.cs
- Controller/Heroes/Necro/CharacterCards/UndeadCardController.cs
- DeckLists/Hero/NecroDeckList.json
- Testing/Heroes/NecroTests.cs
Tracking PR for Necro Peer Review
> The necro peer review

- Testing/BaseTest.cs
All BaseTest functions that take an identifier return the Card or Cards selected.
PrintSeparator print output a little prettier
> Test Framework Enhancements

- Testing/Heroes/TheStrangerTests.cs
Random Test Failures on TheStranger InnateTest failure, fixes Decision selection to correct.
> AdHoc-TheStranger-random Innate Test failures

- Docs/CONTRIBUTING.md
- README.md
front page updates and some more words in contributing
> doco update

- Controller/Villains/Gray/Cards/AlistarWintersCardController.cs
- Controller/Villains/Gray/Cards/BlightTheLandCardController.cs
- Controller/Villains/Gray/Cards/ChainReactionCardController.cs
- Controller/Villains/Gray/Cards/ContaminationCardController.cs
- Controller/Villains/Gray/Cards/CriticalMassCardController.cs
- Controller/Villains/Gray/CharacterCards/GrayCharacterCardController.cs
- DeckLists/Villain/GrayDeckList.json
Initialize:
Character Card
Critical Mass
Create:
Alistar Winters
Blight The Land
Chain Reaction
Contamination
> Create 4 cards Initialize 2

- Docs/manifest.json
- README.md
Added deck to manifest.json
Removed in progress from read me
> Catacombs Manifest + readme

- Controller/Environments/TheWanderingIsle/CardSubClasses/TheWanderingIsleCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/AmphibiousAssaultCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/AncientParasiteCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/BarnacleHydraCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/ExposedLifeforceCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/IslandquakeCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/SongOfTheDeepCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/SubmergeCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/TeryxCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/ThroughTheHurricaneCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/TimedDetonatorCardController.cs
- Testing/Environments/TheWanderingIsleTests.cs
Tracking PR for TheWanderIsle Peer Review
> The wandering isle peer review

- DeckLists/Hero/MalichaeDeckList.json
Decklist correction to close #72.
> Issue 72: incorrect body text in decklist compared to reference card

- Controller/Environments/TheWanderingIsle/Cards/AmphibiousAssaultCardController.cs
- Testing/Environments/TheWanderingIsleTests.cs
> Issue #109 - corrected StartOfTurnTrigger being in constuctor.

- Controller/Heroes/DocHavoc/Cards/PhosphorBlastCardController.cs
> Fixes #115 (wrong card source)

- Controller/Heroes/TangoOne/Cards/SniperRifleCardController.cs
> Updated SniperRifle Discard and Destroy actions with card source.

- Controller/Heroes/DocHavoc/Cards/DocsFlaskCardController.cs
- DeckLists/Hero/DocHavocDeckList.json
Corrected typo in decklist
reviewed card controller for power numerals and cleared up unneeded casts.
> Fix issue #126

- Controller/Heroes/Necro/CardSubClasses/UndeadCardController.cs
- Controller/Heroes/Necro/Cards/AbominationCardController.cs
- Controller/Heroes/Necro/Cards/DemonicImpCardController.cs
- Controller/Heroes/Necro/Cards/GhoulCardController.cs
- Controller/Heroes/Necro/Cards/NecroZombieCardController.cs
- Controller/Heroes/Necro/Cards/PossessedCorpseCardController.cs
Changed method of changing max HP which now is a coroutine, so it updates the UI automatically
NOTE: This is not a fix for the in hand display issue, which as of right now we do not have a solution for.
> Fix of 77 in play issue

- Controller/Environments/TheWanderingIsle/Cards/AncientParasiteCardController.cs
- Testing/Environments/TheWanderingIsleTests.cs
Fixed trigger condition to only damage to Ancient Parasite
Updated test
> Issue #127

- Controller/Heroes/Baccarat/CardSubClasses/AceOfCardController.cs
- Controller/Heroes/Baccarat/Cards/AceOfSaintsCardController.cs
- Controller/Heroes/Baccarat/Cards/AceOfSinnersCardController.cs
- Controller/Heroes/Baccarat/Cards/BringDownTheHouseCardController.cs
- Controller/Heroes/Baccarat/Cards/GraveyardBridgeCardController.cs
- Controller/Heroes/Baccarat/CharacterCards/BaccaratCharacterCardController.cs
- DeckLists/Environment/FSCContinuanceWandererDeckList.json
- Testing/Heroes/BaccaratTests.cs
Closes #89, Closes #75 - created a subclass for both of these cards
Closes #116, 
Closes #118, 
Closes #130, 
Closes #76
> Bugfixes Baccarat and FSC 

- Controller/Heroes/TheStranger/CardSubClasses/GlyphCardController.cs
Remade damage prevention response, utilizing the if pretend function
Closing #68
> Fixed issue 68

- Controller/Heroes/Necro/Cards/TalismanCardController.cs
- Testing/Heroes/NecroTests.cs
Added check that card was either actually destroyed or incapped or removed from the game
> Fixed issue #144

- Controller/Heroes/Malichae/CardSubClasses/DjinnOngoingController.cs
- Controller/Heroes/Malichae/Cards/GrandBathielCardController.cs
- Controller/Heroes/Malichae/Cards/GrandEzaelCardController.cs
- Controller/Heroes/Malichae/Cards/GrandReshielCardController.cs
- Controller/Heroes/Malichae/Cards/GrandSomaelCardController.cs
- Controller/Heroes/Malichae/Cards/HighBathielCardController.cs
- Controller/Heroes/Malichae/Cards/HighEzaelCardController.cs
- Controller/Heroes/Malichae/Cards/HighReshielCardController.cs
- Controller/Heroes/Malichae/Cards/HighSomaelCardController.cs
- DeckLists/Hero/MalichaeDeckList.json
- Testing/Heroes/MalichaeTests.cs
Reworked how th Djinn Ongoing powers work.  The powers are now granted to the base Djinn and are triggered from that Djinn directly just like Captains Cosmic's Cosmic Weapon.
also fixed issue #134
> issue #69 - Djinn Onging Power UI

- Controller/Heroes/DocHavoc/Cards/BrawlerCardController.cs
- Controller/Heroes/DocHavoc/Cards/CauterizeCardController.cs
- Controller/Heroes/DocHavoc/Cards/DocsFlaskCardController.cs
- Controller/Heroes/DocHavoc/Cards/FieldDressingCardController.cs
- Controller/Heroes/DocHavoc/Cards/GasMaskCardController.cs
- Controller/Heroes/DocHavoc/Cards/ImmediateEvacCardController.cs
- Controller/Heroes/DocHavoc/Cards/ImprovisedMineCardController.cs
- Controller/Heroes/DocHavoc/Cards/PainkillersCardController.cs
- Controller/Heroes/DocHavoc/Cards/PhosphorBlastCardController.cs
- Controller/Heroes/DocHavoc/Cards/RapidRegenCardController.cs
- Controller/Heroes/DocHavoc/Cards/RecklessChargeCardController.cs
- Controller/Heroes/DocHavoc/Cards/SearchAndRescueCardController.cs
- Controller/Heroes/DocHavoc/Cards/StimShotCardController.cs
- Controller/Heroes/DocHavoc/Cards/SyringeDartsCardController.cs
- Controller/Heroes/DocHavoc/Cards/UnstableSerumCardController.cs
- Controller/Heroes/DocHavoc/CharacterCards/DocHavocCharacterCardController.cs
- DeckLists/Hero/DocHavocDeckList.json
- Testing/Heroes/DocHavocTests.cs
Fixes for issue #90 & #86 
Some general cleanup of card text based on replication testing.
Deferred Improvised Mine issue for now.
> Doc havoc Issue Fixes #90 & #86

- Controller/Heroes/TheStranger/CardSubClasses/GlyphCardController.cs
- Controller/Heroes/TheStranger/CardSubClasses/RuneCardController.cs
- Controller/Heroes/TheStranger/Cards/FlickeringWebCardController.cs
- Controller/Heroes/TheStranger/Cards/GlyphOfDecayCardController.cs
- Controller/Heroes/TheStranger/Cards/MarkOfDestructionCardController.cs
- Testing/Heroes/TheStrangerTests.cs
Fixes to issues 160, 152, 149, and 148
> Stranger fixes

- Controller/Heroes/TangoOne/Cards/OneShotOneKillCardController.cs
- Testing/Heroes/TangoOneTests.cs
> Add special string for number of cards in hand, update test

- CauldronMods.csproj
- Controller/Heroes/LadyOfTheWood/Cards/LadyOfTheWoodsRebirthCardController.cs
- Controller/Heroes/LadyOfTheWood/Cards/NobilityOfDuskCardController.cs
- DeckLists/Hero/LadyOfTheWoodDeckList.json
- Testing/Heroes/LadyOfTheWoodTests.cs
> Lady of the woods issue167/168

- Controller/Heroes/TangoOne/Cards/PsionicSuppressionCardController.cs
- Controller/Heroes/TangoOne/Cards/WetWorkCardController.cs
> Fixes issues 88, 156

- Controller/Villains/Gray/CardSubClasses/GrayCardController.cs
- Controller/Villains/Gray/Cards/AlistarWintersCardController.cs
- Controller/Villains/Gray/Cards/BlightTheLandCardController.cs
- Controller/Villains/Gray/Cards/ChainReactionCardController.cs
- Controller/Villains/Gray/Cards/ContaminationCardController.cs
- Controller/Villains/Gray/Cards/CriticalMassCardController.cs
- Controller/Villains/Gray/Cards/HeavyRadiationCardController.cs
- Controller/Villains/Gray/Cards/IrradiatedTouchCardController.cs
- Controller/Villains/Gray/Cards/LivingReactorCardController.cs
- Controller/Villains/Gray/Cards/MutatedWildlifeCardController.cs
- Controller/Villains/Gray/Cards/NuclearFireCardController.cs
- Controller/Villains/Gray/Cards/RadioactiveCascadeCardController.cs
- Controller/Villains/Gray/Cards/UnstableIsotopeCardController.cs
- Controller/Villains/Gray/Cards/UnwittingHenchmenCardController.cs
- Controller/Villains/Gray/CharacterCards/GrayCharacterCardController.cs
- Controller/Villains/Gray/CharacterCards/GrayTurnTakerController.cs
- DeckLists/Villain/GrayDeckList.json
- Testing/Villains/GrayTests.cs
- Utility/CodingBugs
Note on Living Reactor:
This should be implementing SelectAndPerformFunction, but when an option is selected nothing happens.
Currently asks for an optional discard, and if no card is discarded then the damage is increased by 1.
> Gray Peer Review

- Controller/Heroes/TheStranger/Cards/GlyphOfCombustionCardController.cs
- Controller/Villains/Anathema/Cards/ExplosiveTransformationCardController.cs
- Controller/Villains/Anathema/Cards/WhipTendrilCardController.cs
Fix #195, Fix #197
I also caught Whip Tendril while verifying.
> Fix some incorrect card sources

- Docs/manifest.json
added gray and st simeons
alphabetized
> manifest update for 0.1.4 release

- DeckLists/Environment/TheChasmOfAThousandNightsDeckList.json
- DeckLists/Environment/TheCybersphereDeckList.json
- DeckLists/Environment/TheWanderingIsleDeckList.json
- DeckLists/Hero/TheKnightDeckList.json
- DeckLists/Hero/TheStrangerDeckList.json
- DeckLists/Villain/TheInfernalChoirDeckList.json
- DeckLists/Villain/TheMistressOfFateDeckList.json
- DeckLists/Villain/TheRamDeckList.json
This ignores the thes for sorting
> Adding Sort Names

- CauldronMods.csproj
sent manfest.json to content and set the output to the debug folder
set deterministic flag, deterministic output
set pdb only to remove local compile paths
> tweaks to the csproj file

- Controller/Heroes/LadyOfTheWood/Cards/LadyOfTheWoodsRebirthCardController.cs
- Controller/Heroes/LadyOfTheWood/Cards/SnowshadeGownCardController.cs
- Testing/Heroes/LadyOfTheWoodTests.cs
> Lady of the wood fixes

- Controller/Environments/BlackwoodForest/Cards/DesolationCardController.cs
- Controller/Environments/BlackwoodForest/Cards/MirrorWraithCardController.cs
- DeckLists/Environment/BlackwoodForestDeckList.json
> Blackwood fixes

- Controller/Environments/StSimeonsCatacombs/CardSubClasses/StSimeonsBaseCardController.cs
- Controller/Environments/StSimeonsCatacombs/CardSubClasses/StSimeonsGhostCardController.cs
- Controller/Environments/StSimeonsCatacombs/CardSubClasses/StSimeonsRoomCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/AqueductsCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/BreathStealerCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/CoalKidCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/CursedVaultCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/DarkPassengerCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/GhostCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/LabyrinthGuideCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/LivingGeometryCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/PanicCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/PoltergeistCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/PossessorCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/RoomCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/SacrificialShrineCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/ScurryingEvilCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/StSimeonsCatacombsCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/StSimeonsCatacombsInstructionsCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/TerriblePresenceCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/TortureChamberCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/TwistingPassagesCardController.cs
- Controller/Environments/StSimeonsCatacombs/TurnTaker/StSimeonsCatacombsTurnTakerController.cs
- Controller/Heroes/DocHavoc/Cards/BrawlerCardController.cs
- Testing/Environments/StSimeonsCatacombsTests.cs
Closes #213 
Closes #212 
Closes #214 
Closes #216
> Catacomb - Rework and Issue Fixes

- Controller/Environments/BlackwoodForest/Cards/DenseBramblesCardController.cs
- Controller/Environments/BlackwoodForest/Cards/DesolationCardController.cs
- Controller/Environments/BlackwoodForest/Cards/DontStrayFromThePathCardController.cs
- Controller/Environments/BlackwoodForest/Cards/MirrorWraithCardController.cs
- Controller/Environments/BlackwoodForest/Cards/OvergrownCathedralCardController.cs
- Controller/Environments/BlackwoodForest/Cards/ShadowStalkerCardController.cs
- Controller/Environments/BlackwoodForest/Cards/ShadowWeaverCardController.cs
- Controller/Environments/BlackwoodForest/Cards/TheBlackTreeCardController.cs
- Controller/Environments/BlackwoodForest/Cards/TheHoundCardController.cs
- Controller/Environments/BlackwoodForest/Cards/VengefulSpiritsCardController.cs
- Controller/Environments/BlackwoodForest/Cards/WillOTheWispCardController.cs
* Code cleanup
* Added some special strings
> BW Code cleanup

- Controller/Environments/BlackwoodForest/Cards/OldBonesCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
Fixes #176 
* Reveal card before moving to deck
* Code cleanup
* Adjust Old Bones tests to check revealed area
> Issue 176 Reveal card before moving to deck

- Controller/Heroes/DocHavoc/Cards/BrawlerCardController.cs
- Controller/Heroes/DocHavoc/Cards/CauterizeCardController.cs
- Controller/Heroes/DocHavoc/Cards/ImmediateEvacCardController.cs
- Controller/Heroes/DocHavoc/CharacterCards/DocHavocCharacterCardController.cs
added missing card source to Brawler
reviewed cards for other instances
> fix for issue 213

- Controller/Environments/TheWanderingIsle/Cards/AmphibiousAssaultCardController.cs
- Testing/Environments/TheWanderingIsleTests.cs
Not an option to deal damage if its no longer in play
Players get to select the order to sources dealing damage
> Fixed Issue #198

- Controller/Environments/BlackwoodForest/Cards/DenseBramblesCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
Fixes #178 
* Add special string showing which targets Dense Brambles is currently giving immunity to
> Issue 178 - Add special string

- Controller/Heroes/TangoOne/CharacterCards/GhostOpsTangoOneCharacterCardController.cs
- Controller/Heroes/TangoOne/CharacterCards/PastTangoOneCharacterCardController.cs
- Testing/Heroes/TangoOnePromoTests.cs
* Add Ghost Ops Tango One
* Add 1929 Tango One
* Promo tests
> Tango one promos

- Controller/Villains/TheRam/Cards/GrapplingClawCardController.cs
> the ram special sting fix

- Controller/Environments/BlackwoodForest/Cards/DenseBramblesCardController.cs
- Controller/Environments/BlackwoodForest/Cards/DesolationCardController.cs
- Controller/Environments/BlackwoodForest/Cards/OvergrownCathedralCardController.cs
* Fix for #234  
* Fix for #235
* Change to special string in Dense Brambles from suggestion from @Vilnor
> Blackwood Forest - issue fixes #234, #235

- DeckLists/Environment/FSCContinuanceWandererDeckList.json
fixes issue #264, incorrect H -2 display in decklist
> issue264-fsc-combat-cyborg-decklist-typo

- Controller/Heroes/DocHavoc/Cards/RecklessChargeCardController.cs
- Controller/Heroes/Malichae/Cards/UnshackledCardController.cs
- Controller/Heroes/TheStranger/Cards/MarkOfQuickeningCardController.cs
added AddThisCardControllerToList(CardControllerListType.IncreasePhaseActionCount) to cards that increase Phase Action card to match base implementation.
> Several - fix for issue #159 - Cards not added to IncreasePhaseActionCount list

- DeckLists/Environment/TheWanderingIsleDeckList.json
> Fix for issue #274

- Controller/Heroes/DocHavoc/CharacterCards/FirstResponseDocHavocCharacterCardController.cs
- DeckLists/Hero/DocHavocDeckList.json
- Testing/Heroes/DocHavocPromoTests.cs
* Implement card
* Implement tests
> First Response Doc Havoc promo

- Controller/Environments/TheWanderingIsle/Cards/AncientParasiteCardController.cs
> WanderingIsle - fix for #278

- Controller/Heroes/Vanish/Cards/BlindsideJumpCardController.cs
- Testing/Heroes/VanishTests.cs
blindside jump's status effect was trying to be 'smart'
added test for redirection application
> Vanish - fix for issue 276

- Art/Atlas/AnathemaAtlas0.json
- Art/Atlas/BaccaratAtlas0.json
- Art/Atlas/DendronAtlas0.json
- Art/Atlas/DocHavocAtlas0.json
- Art/Atlas/GrayAtlas0.json
- Art/Atlas/HalberdExperimentalResearchCenterAtlas0.json
- Art/Atlas/LadyOfTheWoodAtlas0.json
- Art/Atlas/MalichaeAtlas0.json
- Art/Atlas/NecroAtlas0.json
- Art/Atlas/QuicksilverAtlas0.json
- Art/Atlas/StSimeonsCatacombsAtlas0.json
- Art/Atlas/StarlightsAtlas0.json
- Art/Atlas/TangoOneAtlas0.json
- Art/Atlas/TheKnightAtlas0.json
- Art/Atlas/TheRamAtlas0.json
- Art/Atlas/TheStrangerAtlas0.json
- Art/Atlas/TiamatAtlas0.json
- Art/Atlas/TiamatAtlas1.json
- Art/Atlas/VanishAtlas0.json
- Art/Atlas/WanderingIsleAtlas0.json
> Art assest

- Controller/Environments/FSCContinuanceWanderer/Cards/ParadoxIntrusionCardController.cs
- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdAlphaCardController.cs
- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdEtherCardController.cs
- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdFoamcoreCardController.cs
- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdOmegaCardController.cs
- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdPlasmaCardController.cs
- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdSirenCardController.cs
- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdSplinterCardController.cs
- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdZephyrCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/CursedVaultCardController.cs
- Controller/Environments/StSimeonsCatacombs/Cards/TortureChamberCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/AmphibiousAssaultCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/TeryxCardController.cs
- Controller/Heroes/DocHavoc/Cards/ImmediateEvacCardController.cs
- Controller/Heroes/Necro/CardSubClasses/NecroCardController.cs
- Controller/Heroes/Quicksilver/Cards/FrenziedMeleeCardController.cs
- Controller/Heroes/Starlight/Cards/WarpHaloCardController.cs
- Controller/Heroes/TheStranger/Cards/GlyphOfPerceptionCardController.cs
- Controller/Villains/Anathema/Cards/TheStuffOfNightmaresCardController.cs
- Controller/Villains/Dendron/Cards/DarkDesignCardController.cs
- Controller/Villains/Dendron/Cards/LivingInkCardController.cs
- Controller/Villains/Gray/Cards/MutatedWildlifeCardController.cs
- Controller/Villains/TheRam/CharacterCards/TheRamCharacterCardController.cs
- Controller/Villains/Tiamat/CardSubClasses/TiamatCharacterCardController.cs
using base.IsVillain(c) as opposed to c.IsVillain on hero cards so that Maze of Mirrors can correctly intercept them.
> Maze of mirrors compliance

- Controller/Villains/Gray/Cards/LivingReactorCardController.cs
- Testing/Villains/GrayTests.cs
Closes #242 - No longer asks for discard/increase if the target would not take damage. ie. immune to damage
> Gray Bug Fix

- Art/Atlas/AnathemaAtlas0.json
- Art/Atlas/FSCContinuanceWandererAtlas0.json
- Art/Atlas/LadyOfTheWoodAtlas0.json
- Art/Atlas/NecroAtlas0.json
- Art/Atlas/StSimeonsCatacombsAtlas0.json
- Art/Atlas/TheCybersphereAtlas0.json
- Art/Atlas/TheWanderingIsleAtlas0.json
- Controller/Villains/Gray/Cards/AlistairWintersCardController.cs
- DeckLists/Villain/GrayDeckList.json
- Testing/Villains/GrayTests.cs
Closes #309
Closes #310
Closes #313
Closes #316
Closes #318
Closes #319
> Small Art fixes

- Controller/Heroes/LadyOfTheWood/Cards/SnowshadeGownCardController.cs
- Testing/Heroes/LadyOfTheWoodTests.cs
> Use AmountActuallyGained for Snowshade Gown's After trigger

- DeckLists/Hero/BaccaratDeckList.json
- DeckLists/Hero/DocHavocDeckList.json
- DeckLists/Hero/LadyOfTheWoodDeckList.json
- DeckLists/Hero/MalichaeDeckList.json
- DeckLists/Hero/NecroDeckList.json
- DeckLists/Hero/QuicksilverDeckList.json
- DeckLists/Hero/StarlightDeckList.json
- DeckLists/Hero/TangoOneDeckList.json
- DeckLists/Hero/TheKnightDeckList.json
- DeckLists/Hero/TheStrangerDeckList.json
- DeckLists/Hero/VanishDeckList.json
and decklist stubs for the new variants
> More Opening Lines

- Controller/Heroes/Quicksilver/Cards/IronRetortCardController.cs
- Controller/Heroes/Quicksilver/Cards/LiquidMetalCardController.cs
- Controller/Heroes/Quicksilver/Cards/MalleableArmorCardController.cs
Closes #265 - Made Iron Retort Timing After
Closes #261 - Made Liquid Metal Combo playing optional
> Quicksilver bugfixes

- Controller/Heroes/LadyOfTheWood/Cards/NobilityOfDuskCardController.cs
- Controller/Heroes/TheStranger/CardSubClasses/GlyphCardController.cs
Nobility of Dusk had the same issue
> fix for issue 315

- Controller/Heroes/Necro/CharacterCards/NecroCharacterCardController.cs
- Testing/Heroes/NecroTests.cs
> Adjusted necro incap select card criteria

- Art/Atlas/StarlightAtlas0.json
> Modified atlas to line up constellation art work

- Controller/Heroes/TheKnight/Cards/PlateHelmCardController.cs
- Controller/Heroes/TheKnight/Cards/PlateMailCardController.cs
- Testing/Heroes/TheKnightTests.cs
added test
note test will fail without updated base test
> fix for issue 299

- Controller/Heroes/Quicksilver/Cards/MirrorShardCardController.cs
- Testing/Heroes/QuicksilverTests.cs
I learned something about DealDamageActions which makes Mirror Shard much less janky.
> Improve Quicksilver's Mirror Shard implementation

- Controller/Environments/BlackwoodForest/Cards/DenseBramblesCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
Fixes #345 and most of #343 - those tests check behavior that would *ideally* work, but is currently impossible due to the engine.
> Fix Blackwood tests, Dense Brambles

- Testing/Environments/BlackwoodForestTests.cs
- Testing/Environments/NorthsparTests.cs
- Testing/Heroes/VanishTests.cs
- Testing/Villains/DendronTests.cs
Fixes #351, #353, #354, #356, #357, and #360
> Test seed issues

- Controller/Heroes/Vanish/Cards/TacticalRelocationCardController.cs
- Testing/Heroes/VanishTests.cs
> Fix Vanish's Tactical Relocation UI

- Controller/Villains/Anathema/Cards/BiofeedbackCardController.cs
- Testing/Villains/AnathemaTests.cs
> Anathema Biofeedback

- Controller/Environments/StSimeonsCatacombs/Cards/BreathStealerCardController.cs
- Controller/Villains/Anathema/Cards/KnuckleDraggerCardController.cs
- Testing/Villains/AnathemaTests.cs
> Fixes for 362 and 364

- Controller/Heroes/TheStranger/Cards/MarkOfTheFadedCardController.cs
Added checks for not incapped, not out of game, and not off to the side
Closes #390
> Fix for #390

- Controller/Villains/Tiamat/Cards/AlterationCardController.cs
> Tiamat Alteration Order of Play Fix for #419

- Controller/Environments/StSimeonsCatacombs/Cards/PanicCardController.cs
- Testing/Environments/StSimeonsCatacombsTests.cs
> Fixes for #418

- Controller/Villains/Vector/CharacterCards/VectorCharacterCardController.cs
- Testing/Villains/VectorTests.cs
> Fix Vector flip

- Controller/Heroes/Baccarat/CharacterCards/AceOfSwordsBaccaratCharacterCardController.cs
- Controller/Heroes/Baccarat/CharacterCards/BaccaratCharacterCardController.cs
Rather than it silently discarding cards for base and Swords Baccarats there's now a pop up
> Popup which card gets discarded

- Controller/Villains/Gray/Cards/ContaminationCardController.cs
corrected card criteria
fix for issue #385
> Gray -  Contamination

- Controller/Heroes/TangoOne/Cards/CriticalHitCardController.cs
> Critical Hit's damage boost shows in the UI

- Controller/Heroes/Titan/Cards/StubbornGoliathCardController.cs
- Testing/Heroes/TitanTests.cs
Fix #445, fix #452 
Also, the AllowFastCoroutines bit works.
> Fix stubborn goliath

- Controller/Environments/BlackwoodForest/Cards/OvergrownCathedralCardController.cs
> #471 Check to make sure damage was done before initiating deal damage response

- Controller/Heroes/Baccarat/CharacterCards/AceOfSwordsBaccaratCharacterCardController.cs
- Testing/Heroes/BaccaratVariantTests.cs
Ace of Swords will now allow the player to pick number to play before playing them
> Add Select Number to Ace of Swords

- .editorconfig
- Controller/Environments/StSimeonsCatacombs/Cards/StSimeonsCatacombsInstructionsCardController.cs
- Controller/Heroes/Baccarat/CharacterCards/AceOfSorrowsBaccaratCharacterCardController.cs
- Controller/Heroes/Baccarat/CharacterCards/AceOfSwordsBaccaratCharacterCardController.cs
- Controller/Heroes/Baccarat/CharacterCards/BaccaratCharacterCardController.cs
- Controller/Heroes/Baccarat/CharacterCards/PastBaccaratCharacterCardController.cs
- Controller/Heroes/Quicksilver/CardSubClasses/QuicksilverSubCharacterCardController.cs
- Controller/Heroes/Quicksilver/Cards/ComboChainCardController.cs
- Controller/Heroes/Quicksilver/Cards/ForestOfNeedlesCardController.cs
- Controller/Heroes/Quicksilver/Cards/FrenziedMeleeCardController.cs
- Controller/Heroes/Starlight/CharacterCards/StarlightCharacterCardController.cs
- Controller/Heroes/TangoOne/Cards/CriticalHitCardController.cs
- Controller/Heroes/TheStranger/Cards/MarkOfTheBloodThornCardController.cs
- Controller/Heroes/TheStranger/Cards/MarkOfTheBoneLeechCardController.cs
- Controller/Heroes/Titan/Cards/ImmolateCardController.cs
- Controller/Heroes/Titan/CharacterCards/MinistryOfStrategicScienceTitanCharacter.cs
- Controller/Villains/Dendron/Cards/ChokingInscriptionCardController.cs
- Controller/Villains/SwarmEater/Cards/SubterranAugCardController.cs
- Controller/Villains/Tiamat/Cards/ElementOfLightningCardController.cs
- Controller/Villains/Vector/Cards/AnticoagulantCardController.cs
- Controller/Villains/Vector/Cards/EliteTrainingCardController.cs
- Controller/Villains/Vector/Cards/VirulentBladeCardController.cs
- Controller/Villains/Vector/Cards/VrRazortailCardController.cs
- Controller/Villains/Vector/CharacterCards/VectorCharacterCardController.cs
- Testing/BaseTest.cs
- Testing/Environments/NorthsparTests.cs
- Testing/Villains/AnathemaTests.cs
- Testing/Villains/TheRamTests.cs
went through the warning, messages, and code analysis messages and cleanup a few hundred. 170ish still remain
> Visual Studio warning cleanup

- Controller/Environments/SuperstormAkela/Cards/AscendedEdificeCardController.cs
- Controller/Environments/SuperstormAkela/Cards/ScatterburstCardController.cs
- Controller/Environments/SuperstormAkela/Cards/SkulkingIntermediaryCardController.cs
- Controller/Environments/SuperstormAkela/Cards/ToppledSkyscraperCardController.cs
- Controller/Environments/TheWanderingIsle/Cards/ExposedLifeforceCardController.cs
- Controller/Villains/Gray/Cards/BlightTheLandCardController.cs
- Controller/Villains/Gray/Cards/ContaminationCardController.cs
- Controller/Villains/Gray/Cards/RadioactiveCascadeCardController.cs
- Controller/Villains/Gray/CharacterCards/GrayCharacterCardController.cs
- Controller/Villains/SwarmEater/Cards/AbsorbedNanitesCardController.cs
- Controller/Villains/SwarmEater/Cards/SubterranAugCardController.cs
- Controller/Villains/SwarmEater/CharacterCards/SwarmEaterCharacterCardController.cs
- Controller/Villains/Tiamat/CardSubClasses/HydraTiamatCharacterCardController.cs
- Controller/Villains/Tiamat/CharacterCards/ElementalHydra/HydraEarthTiamatCharacterCardController.cs
- Controller/Villains/Vector/CharacterCards/VectorCharacterCardController.cs
changed card.IsVillain and card.IsVillainTarget to IsVillain(card) and IsVillainTarget(card) to ensure correct function with effects that change card designations. Maze of Mirrors being the main one known.
> isVillain & IsVillainTarget cleanup

- Controller/Environments/TheCybersphere/CardSubClasses/TheCybersphereCardController.cs
- Controller/Environments/TheCybersphere/Cards/B3h3mthCardController.cs
- Controller/Environments/TheCybersphere/Cards/Dr3DntCardController.cs
- Controller/Environments/TheCybersphere/Cards/Fo551lCardController.cs
- Controller/Environments/TheCybersphere/Cards/Gho5tCardController.cs
- Controller/Environments/TheCybersphere/Cards/GlitchCardController.cs
- Controller/Environments/TheCybersphere/Cards/H3l1xCardController.cs
- Controller/Environments/TheCybersphere/Cards/HolocycleRaceCardController.cs
- Controller/Environments/TheCybersphere/Cards/HologameArenaCardController.cs
- Controller/Environments/TheCybersphere/Cards/InfectedFirewallCardController.cs
- Controller/Environments/TheCybersphere/Cards/InfectedHoloweaponCardController.cs
- Controller/Environments/TheCybersphere/Cards/N1nj4CardController.cs
- Controller/Environments/TheCybersphere/Cards/ReplicationCardController.cs
- Controller/Environments/TheCybersphere/Cards/Sp4rkCardController.cs
- Controller/Environments/TheCybersphere/Cards/SystemCrashCardController.cs
- Controller/Environments/TheCybersphere/Cards/YourMindMakesItRealCardController.cs
obliveon proofing
linq card critera text
base class abstract
> Cybersphere review, minor fixup

- DeckLists/Villain/TheMistressOfFateDeckList.json
- Testing/AssemblyTests.cs
Updated small icon list for pass for cricket
> Added remaining Radiant & Sonic Decklist icons to approved list

- Controller/Environments/TheWanderingIsle/Cards/BarnacleHydraCardController.cs
- Controller/Heroes/LadyOfTheWood/CharacterCards/LadyOfTheWoodCharacterCardController.cs
- Controller/Heroes/Quicksilver/Cards/TestSubjectHalberdCardController.cs
- Controller/Heroes/TheStranger/Cards/UnweaveCardController.cs
- Controller/Villains/Anathema/CharacterCards/AnathemaCharacterCardController.cs
- Controller/Villains/Tiamat/Cards/HealingMagicCardController.cs
- Controller/Villains/Vector/Cards/HyperactiveImmuneSystemCardController.cs
- Controller/Villains/Vector/Cards/SupervirusCardController.cs
- Testing/BaseTest.cs
- Testing/Heroes/DocHavocTests.cs
- Testing/Villains/AnathemaTests.cs
> Added CardSources to GainHP

- Controller/Heroes/MagnificentMara/CardSubClasses/MaraUtilityCharacterCardController.cs
> Mara Fixes - Fix for #510  and #508

- Controller/Heroes/Cypher/CardSubClasses/AugBaseCardController.cs
- Controller/Heroes/Cypher/CardSubClasses/CypherBaseCardController.cs
- Controller/Heroes/Cypher/CardSubClasses/CypherBaseCharacterCardController.cs
- Controller/Heroes/Cypher/CardSubClasses/PhaseIncreasesAugCardController.cs
- Controller/Heroes/Cypher/Cards/BackupPlanCardController.cs
- Controller/Heroes/Cypher/Cards/CyberdefenseCardController.cs
- Controller/Heroes/Cypher/Cards/CyberintegrationCardController.cs
- Controller/Heroes/Cypher/Cards/CyborgBlasterCardController.cs
- Controller/Heroes/Cypher/Cards/CyborgPunchCardController.cs
- Controller/Heroes/Cypher/Cards/ElectroOpticalCloakCardController.cs
- Controller/Heroes/Cypher/Cards/FusionAugCardController.cs
- Controller/Heroes/Cypher/Cards/HackingProgramCardController.cs
- Controller/Heroes/Cypher/Cards/HeuristicAlgorithmCardController.cs
- Controller/Heroes/Cypher/Cards/InitiatedUpgradeCardController.cs
- Controller/Heroes/Cypher/Cards/NaniteSurgeCardController.cs
- Controller/Heroes/Cypher/Cards/NetworkedAttackCardController.cs
- Controller/Heroes/Cypher/Cards/NeuralInterfaceCardController.cs
- Controller/Heroes/Cypher/Cards/RapidPrototypingCardController.cs
- Controller/Heroes/Cypher/Cards/RebuiltToSucceedCardController.cs
- Controller/Heroes/Cypher/Cards/RetinalAugCardController.cs
- Controller/Heroes/Cypher/CharacterCards/CypherCharacterCardController.cs
fixed #497 
fixed #502 
fixed #501 
Added special strings
> Cypher - Special Strings & Issues

- Controller/Villains/Vector/Cards/SupervirusCardController.cs
- Controller/Villains/Vector/Cards/UndiagnosedSubjectCardController.cs
> Vector Fixes - Fixes #507 and #512

- Controller/Heroes/LadyOfTheWood/Cards/SerenityOfDawnCardController.cs
Serenity of dawn allows auto draw
Closes #485
> Fix for #485 LotW

- Testing/Environments/NorthsparTests.cs
- Testing/Heroes/CricketVariantTests.cs
- Testing/Villains/AnathemaTests.cs
> Seed based fixes

- Controller/Heroes/MagnificentMara/CardSubClasses/MaraUtilityCharacterCardController.cs
- Controller/Heroes/MagnificentMara/Cards/HandIsFasterThanTheEyeCardController.cs
- Controller/Heroes/MagnificentMara/Cards/SmokeAndMirrorsCardController.cs
- Testing/Heroes/MagnificentMaraTests.cs
Fixes #510 for real
Fixes #518
> Mara fixes

- Controller/Environments/Northspar/Cards/WhatsLeftOfThemCardController.cs
> Northspar Fix for #524

- Controller/Heroes/Cricket/Cards/EchonavigationCardController.cs
- Controller/Heroes/Cricket/Cards/SubharmonicReceiverCardController.cs
- Controller/Heroes/Quicksilver/CardSubClasses/ComboCardController.cs
- Controller/Heroes/Quicksilver/Cards/LiquidMetalCardController.cs
- Controller/Heroes/Titan/Cards/ObsidianGraspCardController.cs
- Controller/Villains/Tiamat/CardSubClasses/HydraTiamatInstructionsCardController.cs
- Controller/Villains/Tiamat/CharacterCards/ElementalHydra/Instructions/HydraFrigidEarthTiamatInstructionsCardController.cs
- Controller/Villains/Tiamat/CharacterCards/ElementalHydra/Instructions/HydraNoxiousFireTiamatInstructionsCardController.cs
- Controller/Villains/Tiamat/CharacterCards/ElementalHydra/Instructions/HydraThunderousGaleTiamatInstructionsCardController.cs
- Testing/Heroes/TitanTests.cs
- Testing/Villains/TiamatHydraTests.cs
Cricket:
#537 - Echonavigation now allows autodecide
Titan:
#540 - Obsidian Grasp doesn't play an Immolate if the target is destroyed
Quicksilver:
#420 - Liquid Metal pop up now asks if you want to deal yourself damage instead of asking if you want to play Liquid Metal
Tiamat
#545 - Reloading no longer breaks First/Second Head
> Varied bugfixes dec15

- Controller/Heroes/LadyOfTheWood/CharacterCards/MinistryOfStrategicScienceLadyOfTheWoodCharacterCardController.cs
Added check that there are tokens before deal damage trigger occurs
Closes #543
> Fixed #543

- Controller/Heroes/Necro/CardSubClasses/NecroCardController.cs
- Controller/Heroes/Necro/CharacterCards/PastNecroCharacterCardController.cs
- Testing/Heroes/NecroVariantTests.cs
> Fixes #558 1929 Necro Reload Issues

- Controller/Heroes/Cricket/Cards/AcousticDistortionCardController.cs
- Controller/Heroes/DocHavoc/Cards/CauterizeCardController.cs
- Controller/Heroes/LadyOfTheWood/Cards/NobilityOfDuskCardController.cs
- Controller/Heroes/LadyOfTheWood/CharacterCards/MinistryOfStrategicScienceLadyOfTheWoodCharacterCardController.cs
- Controller/Heroes/TheStranger/CardSubClasses/GlyphCardController.cs
- Controller/Heroes/Titan/Cards/TitanformCardController.cs
A couple of other changes:
Cauterize only asks for its effect if the damage is at least 1
MOSS LOTW damage change goes through the GameController so the UI can see it
> Add isActionOptional to several hero card triggers

- Controller/Heroes/DocHavoc/Cards/CauterizeCardController.cs
> Doc Havoc/Malpractice Medico fix

- Controller/Heroes/Cypher/CardSubClasses/PhaseIncreasesAugCardController.cs
- Testing/Heroes/CypherTests.cs
added tests for phase action count
> Fixed #532

- Controller/Villains/SwarmEater/CardSubClasses/AugCardController.cs
- Controller/Villains/SwarmEater/Cards/VenomAugCardController.cs
- Controller/Villains/SwarmEater/CharacterCards/DistributedHivemindSwarmEaterCharacterCardController.cs
- Testing/Villains/SwarmEaterTests.cs
- Testing/Villains/SwarmEaterVariantTests.cs
Keeps absorb abilities through save/load
Hivemind Swarm Eater activates absorb abilities
> Swarm eater fixes

- CauldronMods.csproj
- Controller/Villains/PhaseVillain/CharacterCards/PhaseVillainCharacterCardController.cs
> Fix Phase flip

- Testing/AssemblyTests.cs
updates the test, 200+ opening lines to be fixed :)
> Updated Assemby Test with fancier icon test and new opening lines test

- Controller/Environments/Northspar/Cards/BitterColdCardController.cs
- Controller/Environments/Northspar/Cards/LandingSiteCardController.cs
- Testing/Environments/NorthsparTests.cs
Added check that storedResults is not empty
> northspar fixes

- DeckLists/Hero/DriftDeckList.json
- DeckLists/Hero/GargoyleDeckList.json
- DeckLists/Hero/GyrosaurDeckList.json
- DeckLists/Hero/PyreDeckList.json
- DeckLists/Hero/QuicksilverDeckList.json
- DeckLists/Villain/OutlanderDeckList.json
- DeckLists/Villain/TheRamDeckList.json
added missing adrift promos to decklists.
> adrift decklist update

- Art/Atlas/DendronAtlas0.json
- Art/Atlas/SetupGame0.json
Also fixed the name of Test Subject Drift
> Fix Dendron Variant in Atlases

- CauldronMods/Controller/Villains/Menagerie/CardSubClasses/EnclosureCardController.cs
- CauldronMods/Controller/Villains/Menagerie/CardSubClasses/MenagerieCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/FeedingTimeCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/FeethsmarAlphaCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/HalberdHiveCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/HiredKeeperCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/HyrianSnipeCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/LumobatFlockCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/PrizedCatchCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/SpecimenCollectorCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/TakIshmaelCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/TheMonBeskmaHydricCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/ViewingAperturesCardController.cs
- CauldronMods/Controller/Villains/Menagerie/CharacterCards/MenagerieCharacterCardController.cs
- Testing/Villains/MenagerieTests.cs
Added invisibility for cards under enclosures
I tried using the base.Card.UnderLocation.OverrideIsInPlay = false; but it was causing problems with Viewing apertures. I didn't investigate too much to figure out why
> Menegerie Invisibility

- CauldronMods/Controller/Heroes/TheStranger/CardSubClasses/GlyphCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/CardSubClasses/RuneCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/CardSubClasses/TheStrangerBaseCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/CardSubClasses/TheStrangerBaseCharacterCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/CorruptionCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/FlickeringWebCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/GlyphOfDecayCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/GlyphOfInnervationCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/GlyphOfPerceptionCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/MarkOfDestructionCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/MarkOfTheBoneLeechCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/MarkOfTheFadedCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/TheOldRoadsCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/UnweaveCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/Cards/WhisperedSignsCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/CharacterCards/CornTheStrangerCharacterCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/CharacterCards/PastTheStrangerCharacterCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/CharacterCards/RunecarvedTheStrangerCharacterCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/CharacterCards/TheStrangerCharacterCardController.cs
- CauldronMods/Controller/Heroes/TheStranger/CharacterCards/WastelandRoninTheStrangerCharacterCardController.cs
misc cleanup to remvoe dup code and clean up some decompiler junk
> Added number of runes & number of glyphs via base class.

- CauldronMods/Controller/Heroes/Starlight/Cards/PillarsOfCreationCardController.cs
- CauldronMods/Controller/Heroes/Starlight/CharacterCards/Area51StarlightCharacterCardController.cs
- Testing/Heroes/StarlightTests.cs
- Testing/Heroes/StarlightVariantTests.cs
fix for issue #721
fix for #720
> Starlight Issues

- CauldronMods/Controller/Heroes/MagnificentMara/Cards/HandIsFasterThanTheEyeCardController.cs
- Testing/Heroes/MagnificentMaraTests.cs
> Mara Gene-Bound Banshee + HiFTTE freeze

- CauldronMods/Controller/Environments/BlackwoodForest/Cards/VengefulSpiritsCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/HiredKeeperCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/HyrianSnipeCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/SecuritySphereCardController.cs
> Menagerie CardSource sweep

- CauldronMods/Controller/Heroes/Gargoyle/Cards/LeechFieldCardController.cs
- CauldronMods/Controller/Heroes/Gargoyle/Cards/YourStrengthIsMineCardController.cs
> Leech field decision info

- CauldronMods/Controller/Environments/TheChasmOfAThousandNights/Cards/TevaelCardController.cs
- Testing/Environments/TheChasmOfAThousandNightsTests.cs
> Fix for issue 789: Tavael Indestructibility

- CauldronMods/DeckLists/Villain/TiamatDeckList.json
> fixed issue #796 - Tiamat 2199 Scale Text Size

- CauldronMods/Controller/Environments/VaultFive/CardSubClasses/ArtifactCardController.cs
> fix for issue #787 - Artifacts Rewinding Fix

- CauldronMods/Controller/Environments/StSimeonsCatacombs/Cards/AqueductsCardController.cs
- CauldronMods/DeckLists/Environment/StSimeonsCatacombsDeckList.json
- Testing/Environments/StSimeonsCatacombsTests.cs
> fix for issue #707 - Aqueducts Wrong Timing

- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/AllAboardCardController.cs
- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/HarkinParishJrCardController.cs
- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/RadioPlazaCardController.cs
- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/SSEscapeCardController.cs
- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/TheCervantesClubCardController.cs
- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/ThisJustInCardController.cs
- Testing/Environments/CatchwaterHarborTests.cs
Query wasn't excluding Incap and Out of Game heros.
Reviewed other cards and found the same issue on a few other cards.
> Issue810 the cervantes club

- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/SmoothCriminalCardController.cs
- Testing/CauldronBaseTest.cs
- Testing/Environments/CatchwaterHarborTests.cs
- Testing/Environments/FSCContinuanceWandererTests.cs
I don't know for sure what was the issue, but it seems like it was that it was always using a fixed amount and not dynamic. Adjusted and added tests for dynamic amounts
Closes #808
> Fix for #808 - Smooth Criminal

- CauldronMods/Controller/Environments/VaultFive/CardSubClasses/ArtifactCardController.cs
- Testing/BaseTest.cs
- Testing/Environments/VaultFiveTests.cs
The issue is on some level an engine problem, but this should (I think) get it working once the upcoming update is in.
> Vault Five artifact crash pre-fix

- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftBaseCardController.cs
- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftFocusUtilityCardController.cs
- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftSubCharacterCardController.cs
- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftUtilityCardController.cs
- CauldronMods/Controller/Heroes/Drift/CharacterCards/ThroughTheBreachDriftCharacterCardController.cs
- CauldronMods/Controller/Heroes/Drift/Shift Track/DualShiftTrackUtilityCardController.cs
- CauldronMods/Controller/Heroes/Drift/Shift Track/ShiftTrackUtilityCardController.cs
- CauldronMods/Controller/Heroes/Drift/Shift Track/ThroughTheBreachShiftTrackUtilityCardController.cs
- CauldronMods/DeckLists/Hero/DriftDeckList.json
- Testing/Heroes/DriftDualVariantTests.cs
- Testing/Heroes/DriftTests.cs
- Testing/Heroes/DriftVariantsTests.cs
Fixed ignored tests
removed some duplicated code
Fixed broken decklist on Dual Drift
> Drift review cleanup

- CauldronMods/Controller/Environments/VaultFive/CardSubClasses/ArtifactCardController.cs
- CauldronMods/Controller/Environments/VaultFive/Cards/MomentOfSanityCardController.cs
- CauldronMods/Controller/Heroes/Gargoyle/Cards/MarkForExecutionCardController.cs
- Testing/Environments/VaultFiveTests.cs
- Testing/Heroes/GargoyleTests.cs
> Vault five fixes

- CauldronMods/Controller/Heroes/Gargoyle/Cards/ViolentAssistCardController.cs
> Gargoyle Violent Assist IsActionOptional

- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/HarborCraneCardController.cs
- Testing/Environments/CatchwaterHarborTests.cs
prevent crane from triggering it's move on self damage.
added test, fixed seed test failure
> fix for issue 822

- CauldronMods/Controller/Environments/TheChasmOfAThousandNights/Cards/ThievingCardController.cs
- CauldronMods/Controller/Heroes/Titan/Cards/ImmolateCardController.cs
- CauldronMods/DeckLists/Hero/StarlightDeckList.json
- Testing/Environments/TheChasmOfAThousandNightsTests.cs
- Testing/Heroes/TitanTests.cs
Fixes #821 
This is just the ones I know about, if you have noticed one feel free to add it.
> Did-deal-damage cleanup

- CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/SuperimposedRealitiesCardController.cs
- Testing/Environments/FSCContinuanceWandererTests.cs
> Superimposed Realities put-into-play

- CauldronMods/Controller/Environments/StSimeonsCatacombs/Cards/PossessorCardController.cs
- Testing/Environments/StSimeonsCatacombsTests.cs
> St. Simeon's possessor destroyed mid-play

- CauldronMods/Controller/Heroes/Drift/CharacterCards/DriftTurnTakerController.cs
Tested in game for all variants and this works
> Drift Incap Fix

- CauldronMods/Controller/Environments/BlackwoodForest/Cards/MirrorWraithCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
Formally, it will look for what the other Mirror Wraith is copying and then go copy that.
> Let Mirror Wraith copy another Mirror Wraith

- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/HarkinParishJrCardController.cs
> fix for #905 - Harkin Parish Jr allows auto decide

- CauldronMods/manifest.json
Cleaned up credits section via a strings array
Updated version number
> Manifest updates

- CauldronMods/Controller/Villains/Mythos/CardSubClasses/MythosUtilityCardController.cs
- CauldronMods/Controller/Villains/Mythos/CharacterCards/MythosCharacterCardController.cs
- Testing/Villains/MythosTests.cs
Added safety check to checking the top card when there are no cards in deck
> Mythos softlock fix

- CauldronMods/Controller/Heroes/Necro/CardSubClasses/NecroCardController.cs
- CauldronMods/Controller/Heroes/Necro/CardSubClasses/UndeadCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/AbominationCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/DemonicImpCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/GhoulCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/NecroZombieCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/PossessedCorpseCardController.cs
- Testing/Heroes/NecroTests.cs
> Necro special strings

- CauldronMods/Controller/Heroes/Malichae/Cards/HighReshielCardController.cs
> High Reshiel targeting

- CauldronMods/Controller/Heroes/Starlight/CardSubClasses/StarlightSubCharacterCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/CardSubClasses/TheKnightUtilityCharacterCardController.cs
- CauldronMods/DeckLists/Hero/StarlightDeckList.json
- CauldronMods/DeckLists/Hero/TheKnightDeckList.json
- Testing/Heroes/StarlightVariantTests.cs
Swapping into or out of one of the multi-character promos causes Problems(tm), so we need to prevent it from happening.
> Multi-char promo + Completionist Guise stuff

- CauldronMods/Controller/Environments/DungeonsOfTerror/CardSubClasses/DungeonsOfTerrorUtilityCardController.cs
- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/EnormousPackCardController.cs
- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/HighGroundCardController.cs
- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/RestfulInnCardController.cs
- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/RovingSlimeCardController.cs
- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/StoneWardenCardController.cs
- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/SuspiciousChestCardController.cs
- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/UnderleveledCardController.cs
- Testing/Environments/DungeonsOfTerrorTests.cs
> Changed implementation to allow empty deck/trash to act as if it was a non-fate card

- CauldronMods/Controller/Heroes/Vanish/Cards/FlashReconCardController.cs
- CauldronMods/Controller/Heroes/Vanish/CharacterCards/VanishCharacterCardController.cs
- Testing/Heroes/VanishTests.cs
Show all revealed cards instead of locations.
> Improve Flash Recon Usability

- CauldronMods/Controller/Villains/Menagerie/Cards/MutatedAntCardController.cs
- Testing/Villains/MenagerieTests.cs
> Fix for #884 - Mutated Ant Targetting

- CauldronMods/Controller/Heroes/Baccarat/CharacterCards/AceOfSwordsBaccaratCharacterCardController.cs
Closes #943 
Added check for cards in play and visible to character card
> Fix for #943- Ace of Swords Incap

- CauldronMods/Controller/Villains/Dendron/Cards/ChokingInscriptionCardController.cs
- CauldronMods/Controller/Villains/Dendron/Cards/DarkDesignCardController.cs
- CauldronMods/Controller/Villains/Dendron/Cards/InkScarCardController.cs
- CauldronMods/Controller/Villains/Dendron/Cards/MarkOfTheWrithingNightCardController.cs
- CauldronMods/Controller/Villains/Dendron/Cards/PaintedViperCardController.cs
- CauldronMods/Controller/Villains/Dendron/Cards/StainedWolfCardController.cs
- CauldronMods/Controller/Villains/Dendron/Cards/TintedStagCardController.cs
- CauldronMods/Controller/Villains/Dendron/Cards/UrsaMajorCardController.cs
- CauldronMods/Controller/Villains/Dendron/CharacterCards/DendronCharacterCardController.cs
> Dendron card sources cleanup

- CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/ParadoxIntrusionCardController.cs
- CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/PrehistoricBehemothCardController.cs
- CauldronMods/DeckLists/Environment/DungeonsOfTerrorDeckList.json
- CauldronMods/DeckLists/Environment/FSCContinuanceWandererDeckList.json
- CauldronMods/DeckLists/Environment/HalberdExperimentalResearchCenterDeckList.json
- CauldronMods/DeckLists/Environment/NightloreCitadelDeckList.json
- CauldronMods/DeckLists/Environment/NorthsparDeckList.json
- CauldronMods/DeckLists/Environment/StSimeonsCatacombsDeckList.json
- CauldronMods/DeckLists/Environment/TheWanderingIsleDeckList.json
- CauldronMods/DeckLists/Environment/VaultFiveDeckList.json
- CauldronMods/DeckLists/Environment/WindmillCityDeckList.json
- CauldronMods/DeckLists/Hero/DriftDeckList.json
- CauldronMods/DeckLists/Hero/GyrosaurDeckList.json
- CauldronMods/DeckLists/Hero/MalichaeDeckList.json
- CauldronMods/DeckLists/Hero/TerminusDeckList.json
- CauldronMods/DeckLists/Villain/TheInfernalChoirDeckList.json
- Testing/Environments/FSCContinuanceWandererTests.cs
Closes #919 
Closes #920 
Closes #921 
Closes #922 
Closes #923 
Closes #924 
Closes #925 
Closes #926 
Closes #935 
Closes #945 
Closes #946 
Closes #949 
Closes #950
> Decklist fixes

- DeckBrowser/ExpeditionOblaskPyreCharacterVitals.txt
- DeckBrowser/PyreCharacterVitals.txt
- DeckBrowser/UnstablePyreCharacterVitals.txt
- DeckBrowser/WastelandRoninPyreCharacterVitals.txt
Fix misspelling on Pyre's stats.
> Misspelling fix

- CauldronMods/Controller/Villains/Mythos/Cards/YourDarkestSecretsCardController.cs
- Testing/Villains/MythosTests.cs
> Your Darkest Secrets cleanup

- CauldronMods/Controller/Heroes/Quicksilver/Cards/ForestOfNeedlesCardController.cs
- Testing/Heroes/QuicksilverTests.cs
> Forest of needles damage

- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftSubCharacterCardController.cs
- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftUtilityCardController.cs
> Drift MP crash fix (hopefully)

- CauldronMods/Controller/Environments/NightloreCitadel/Cards/StarlightOfNoomeCardController.cs
- Testing/Environments/NightloreCitadelTests.cs
Starlight of Noome was not healing if she was prevented from dealing damage
> Starlight of noome fix

- CauldronMods/Controller/Environments/SuperstormAkela/Cards/RideTheCurrentsCardController.cs
- Testing/Environments/SuperstormAkelaTests.cs
Closes #988 
I disagree with the notion that it can't choose an empty deck, but it shouldn't be able to select incapped turntakers
> Fix for issue 988 - Ride the Currents Play

- CauldronMods/Controller/Environments/VaultFive/CardSubClasses/ArtifactCardController.cs
- Testing/Environments/VaultFiveTests.cs
> Fix for 993  artifacts and empty decks

- CauldronMods/DeckLists/Environment/FSCContinuanceWandererDeckList.json
> fixed time freeze text

- CauldronMods/Controller/Heroes/Pyre/Cards/GammaBurstCardController.cs
Closes #992 
Per tosx suggestion, the player whose hand was chosen gets to choose the card
Note: I did not test this in multiplayer, as I do not have the setup to do so presently, but I believe this solves the issue
> Pyre Gamma Burst Fix

- CauldronMods/CauldronMods.csproj
- CauldronMods/manifest.json
- README.md
Updated manifest and project properties
Updated Readme
> Versioning Update

- CauldronMods/Controller/Villains/Gray/Cards/LivingReactorCardController.cs
> living reactor ui  improvements

- CauldronMods/DeckLists/Hero/GyrosaurDeckList.json
- Testing/Environments/StSimeonsCatacombsTests.cs
- Testing/Heroes/CricketTests.cs
Gyrosaur decklist had some cards with 5 icons
Chirp0Discards Tests was still discarding
PossessorDestroyMidPlay test had some consistency issues
> Fixes to test suite failures

- CauldronMods/Controller/Environments/NightloreCitadel/Cards/GravityFluctuationCardController.cs
- Testing/Environments/NightloreCitadelTests.cs
> Fix for 1008 - Gravity Fluctuation Looking at Off to the Side Cards

- CauldronMods/CauldronMods.csproj
- CauldronMods/DeckLists/Environment/OblaskCraterDeckList.json
- Testing/Environments/OblaskCraterTests.cs
> Oblask decklist text fix

- CauldronMods/Controller/Environments/NightloreCitadel/Cards/WarpBridgeCardController.cs
- Testing/Environments/NightloreCitadelTests.cs
> Fix for 1016 - Warp Drive and Non-Real Cards

- CauldronMods/manifest.json
added formatting and updated list of playtesters
> credits update

- CauldronMods/Controller/Heroes/TangoOne/CharacterCards/GhostOpsTangoOneCharacterCardController.cs
- Testing/Heroes/TangoOnePromoTests.cs
> Ghost ops incap fix

- CauldronMods/Controller/Heroes/Titan/Cards/UnbreakableCardController.cs
- Testing/Heroes/TitanTests.cs
> Fix for 1033 - Titan's Unbreakable working through Battle Zones

- CauldronMods/DeckLists/Villain/TheMistressOfFateDeckList.json
This allows the {H-1} to render properly
> Updated bullets for mistress of fate

- CauldronMods/Controller/Heroes/Cricket/CharacterCards/RenegadeCricketCharacterCardController.cs
- Testing/Heroes/CricketVariantTests.cs
- Testing/Heroes/MagnificentMaraTests.cs
> Fix for 1038 - Renegade Cricket and Dark Mind

- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/RadioPlazaCardController.cs
- Testing/Environments/CatchwaterHarborTests.cs
> Fix for 1039 - Radio Plaza in Oblivaeon Mode

- CauldronMods/Controller/Heroes/Terminus/Cards/EtherealArmoryCardController.cs
- Testing/Heroes/TerminusTest.cs
Closes #1049 
Refined conditions on ethereal armory's expiring status effects
> Fix for 1049 - Ethereal Armory with Next to Cards that Fall off

- CauldronMods/Controller/Heroes/Terminus/Cards/GuiltyVerdictCardController.cs
- Testing/Heroes/TerminusTest.cs
> Fix for 1050 - Guilty Verdict Triggering Incorrectly

- CauldronMods/Controller/Heroes/TangoOne/Cards/InfiltrateCardController.cs
- CauldronMods/Controller/Heroes/TangoOne/Cards/WetWorkCardController.cs
- Testing/Heroes/TangoOneTests.cs
Fixes to infiltrate and wet work
Closes #1057
> Tango one bug fixes in Oblivaeon

- CauldronMods/Controller/Environments/OblaskCrater/Cards/UnknownHerdsCardController.cs
- Testing/Environments/OblaskCraterTests.cs
> Unknown herds power modification

- CauldronMods/Controller/Heroes/Baccarat/Cards/GraveyardBridgeCardController.cs
- CauldronMods/Controller/Heroes/Echelon/Cards/NeedAWayOutCardController.cs
- CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/NobilityOfDuskCardController.cs
- CauldronMods/Controller/Heroes/Titan/Cards/MisbehaviorCardController.cs
- CauldronMods/Controller/Heroes/Titan/Cards/MoltenVeinsCardController.cs
- CauldronMods/Controller/Villains/TheMistressOfFate/Cards/FadingRealitiesCardController.cs
- CauldronMods/Controller/Villains/TheMistressOfFate/Cards/TheTimelineCardController.cs
This is a first pass of cards I'm currently aware needed custom text.
Closes #1031 
Closes #423
> Custom UI Texts

- CauldronMods/Controller/Villains/TheInfernalChoir/Cards/VagrantHeartPhase2CardController.cs
- Testing/BaseTest.cs
- Testing/Villains/TheInfernalChoirTests.cs
> Fix for 948 - Infernal Choir Discards from an empty deck

- Testing/Heroes/GargoyleTests.cs
This is in relation to issue #954 
I was unable to replicate the bug, so I have closed that issue, but I figure it is still worthwhile to have the test for the future
> violent assist + enhanced senses interaction

- CauldronMods/Controller/Heroes/Cypher/Cards/RebuiltToSucceedCardController.cs
- Testing/Heroes/CypherTests.cs
> Rebuilt to succeed play

- CauldronMods/DeckLists/Hero/MalichaeDeckList.json
- Testing/Heroes/MalichaeTests.cs
> Solomons fire fix

- CauldronMods/Controller/Villains/TheInfernalChoir/Cards/WretchedSymphonyCardController.cs
- Testing/Villains/TheInfernalChoirTests.cs
> Fix for 1098 - Infernal Choir Wretched Symphony Special String Fix

- CauldronMods/Controller/Heroes/Baccarat/CharacterCards/AceOfSwordsBaccaratCharacterCardController.cs
- Testing/Heroes/BaccaratVariantTests.cs
> Baccarat ace of sword UI improvement

- CauldronMods/Controller/Heroes/Vanish/CharacterCards/VanishCharacterCardController.cs
- Testing/Heroes/VanishTests.cs
> Fix for vanish innate power

- CauldronMods/Controller/Heroes/Gargoyle/Cards/DreamcatcherCardController.cs
Closes #1102 
This should not have a skip option at all - removed.
> Fix for 1102 - Gargoyle Dreamcatcher

- CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/LadyOfTheWoodsRebirthCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CardSubClasses/HydraTiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CardSubClasses/TiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/Cards/ElementalFrenzyCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/2199/FutureTiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/ElementalHydra/Instructions/HydraNoxiousFireTiamatInstructionsCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/ElementalHydra/Instructions/HydraThunderousGaleTiamatInstructionsCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/Regular/InfernoTiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/Regular/StormTiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/Regular/WinterTiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/TiamatTurnTakerController.cs
- CauldronMods/DeckLists/Villain/TiamatDeckList.json
- Testing/Villains/TiamatFutureTests.cs
- Testing/Villains/TiamatHydraTests.cs
- Testing/Villains/TiamatTests.cs
Also has a couple of bugfixes around the edges
> Tiamat challenge mode

- CauldronMods/Controller/Heroes/MagnificentMara/Cards/KalpakOfMysteriesCardController.cs
- Testing/Heroes/MagnificentMaraTests.cs
> Kalpak-Ninja interaction 

- CauldronMods/Controller/Villains/SwarmEater/Cards/FireAugCardController.cs
- Testing/Villains/SwarmEaterTests.cs
> Fire aug incap discard

- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftSubCharacterCardController.cs
- CauldronMods/Controller/Heroes/Titan/SubCardClasses/TitanBaseCharacterCardController.cs
- Testing/Heroes/DriftTests.cs
- Testing/Heroes/TitanTests.cs
> Cutout-swap power usability

- CauldronMods/CauldronMods.csproj
- CauldronMods/Controller/Heroes/Gyrosaur/Cards/SphereOfDevastationCardController.cs
Fixes #1169
Logic is based off of GameController.DiscardHand's flow.
> Added check for user setting and logic for discarding all crash cards

- CauldronMods/Controller/Villains/Tiamat/Cards/AcidBreathCardController.cs
> changed GetEnumerator into foreach

- Art/Atlas/EndGameHeroes0.json
- Art/Atlas/HeroLogos0.json
fixed some filename typos in art atlases
> Atlas typo fixes

- CauldronMods/Controller/Villains/Mythos/Cards/DangerousInvestigationCardController.cs
- CauldronMods/Controller/Villains/Mythos/CharacterCards/MythosCharacterCardController.cs
This should make it clearer to players how accumulating tokens on Dangerous Investigation works.
> Mythos and Dangerous Investigation custom decision text

- CauldronMods/DeckLists/Villain/AnathemaDeckList.json
- CauldronMods/DeckLists/Villain/CeladrochDeckList.json
- CauldronMods/DeckLists/Villain/DendronDeckList.json
- CauldronMods/DeckLists/Villain/DynamoDeckList.json
- CauldronMods/DeckLists/Villain/GrayDeckList.json
- CauldronMods/DeckLists/Villain/MenagerieDeckList.json
- CauldronMods/DeckLists/Villain/MythosDeckList.json
- CauldronMods/DeckLists/Villain/OriphelDeckList.json
- CauldronMods/DeckLists/Villain/OutlanderDeckList.json
- CauldronMods/DeckLists/Villain/PhaseVillainDeckList.json
- CauldronMods/DeckLists/Villain/ScreaMachineDeckList.json
- CauldronMods/DeckLists/Villain/SwarmEaterDeckList.json
- CauldronMods/DeckLists/Villain/TheInfernalChoirDeckList.json
- CauldronMods/DeckLists/Villain/TheMistressOfFateDeckList.json
- CauldronMods/DeckLists/Villain/TheRamDeckList.json
- CauldronMods/DeckLists/Villain/TiamatDeckList.json
- CauldronMods/DeckLists/Villain/VectorDeckList.json
The video game uses the format of Oversized Villain cards, `Character enters play 'Title' side up.`
> Villain setup Instructions Consistency

- CauldronMods/Controller/Heroes/Titan/Cards/ForbiddenArchivesCardController.cs
> Forbidden Archives Custom Text

- CauldronMods/Controller/Heroes/Gyrosaur/Cards/SphereOfDevastationCardController.cs
- Testing/Heroes/GyrosaurTests.cs
> Fix for #1104: Sphere of Devastation Improvement

- CauldronMods/Controller/Environments/Northspar/Cards/MakeshiftShelterCardController.cs
> makeshift shelter custom text

- CauldronMods/Controller/Heroes/Gyrosaur/Cards/ReadTheTerrainCardController.cs
Was using the baked in RevealTopCard_PutItBackOrDiscardIt function, but that ignores card source on the yes no decision
Created a custom response based on that method that includes that card source
Closes #1168
> Fix for issue 1168 - Gyrosaur's Read the Terrain Decision Card Source

- CauldronMods/Controller/Heroes/Vanish/Cards/ForewarnedCardController.cs
- Testing/Heroes/VanishTests.cs
> Fix for #1071 - Vanish forewarned Cross Battle Zones

- CauldronMods/Controller/Heroes/Quicksilver/CharacterCards/RenegadeQuicksilverCharacterCardController.cs
- Testing/Heroes/QuicksilverVariantsTests.cs
> Fix for 1085 - Renegade Quicksilver Special String

- CauldronMods/Controller/Heroes/Titan/Cards/ReversalCardController.cs
- Testing/Heroes/TitanTests.cs
> Fix for 1136 - Titan's Reversal Timing Issues

- CauldronMods/Controller/Heroes/Impact/CharacterCards/ImpactCharacterCardController.cs
Added custom text to decision
Changed preview to show a question mark instead of the actual damage amount
Closes #1065
> Impact base power improvements

- CauldronMods/Controller/Heroes/Baccarat/Cards/BringDownTheHouseCardController.cs
- Testing/Heroes/BaccaratTests.cs
> Bring down the house improvements

- CauldronMods/Controller/Heroes/Quicksilver/CharacterCards/RenegadeQuicksilverCharacterCardController.cs
- Testing/Heroes/QuicksilverVariantsTests.cs
> Fix #1086 - Renegade Quicksilver Timing Incap 2

- CauldronMods/Controller/Heroes/Cricket/CharacterCards/WastelandRoninCricketCharacterCardController.cs
- Testing/Heroes/CricketVariantTests.cs
> Wasteland ronin incap 2 oblivaeon

- CauldronMods/Controller/Heroes/Drift/Cards/FutureFocusCardController.cs
- CauldronMods/Controller/Heroes/Drift/Cards/PastFocusCardController.cs
> Drift's Focuses Custom Text

- CauldronMods/Controller/Heroes/Gargoyle/Cards/YourStrengthIsMineCardController.cs
> Gargoyle's Your Strength is Mine - UI Improvement

- CauldronMods/Controller/Heroes/Cricket/CharacterCards/RenegadeCricketCharacterCardController.cs
- Testing/Heroes/CricketVariantTests.cs
> Renegade cricket + Enhanced Senses fix

- CauldronMods/Controller/Heroes/MagnificentMara/Cards/PostHypnoticCueCardController.cs
> Fix for 1170 - Post Hypnotic Gaze Associated Card Pop-up

- CauldronMods/Controller/Villains/TheInfernalChoir/CharacterCards/TheInfernalChoirCharacterCardController.cs
- Testing/Villains/TheInfernalChoirTests.cs
The default ShowIfSpecificCardIsInPlay using AlternateTitleOrTitle which it doesn't cooperate well with for Save and loads.
Copied that method and made a special version using just Title
> Infernal choir special string + Save and Loads

- CauldronMods/Controller/Heroes/Quicksilver/CharacterCards/UncannyQuicksilverCharacterCardController.cs
- Testing/Heroes/QuicksilverVariantsTests.cs
> Uncanny quicksilver Incap Fixes

- CauldronMods/Controller/Heroes/Gargoyle/Cards/AbsorbAndUnleashCardController.cs
- Testing/Heroes/GargoyleTests.cs
> Fix for 1199 - Gargoyle's Absorb and Unleash when Redirected

- CauldronMods/Controller/Villains/TheMistressOfFate/CharacterCards/TheMistressOfFateCharacterCardController.cs
- Testing/Villains/TheMistressOfFateTests.cs
Only activates in actual challenge mode
Only activate on the flip from front to back, not the other direction
> Mistress of Fate challenge fix

- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/FrightenedOnlookersCardController.cs
- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/ThisJustInCardController.cs
> Added optional: true to two Catchwater cards

- CauldronMods/DeckLists/Environment/FSCContinuanceWandererDeckList.json
- CauldronMods/DeckLists/Hero/PyreDeckList.json
- CauldronMods/DeckLists/Villain/TheInfernalChoirDeckList.json
- CauldronMods/DeckLists/Villain/TheRamDeckList.json
> Typo and Icon fixes

- CauldronMods/Controller/Heroes/Echelon/Cards/BreakThroughCardController.cs
> echelon's breakthrough custom ui text

- CauldronMods/Controller/Heroes/Drift/Cards/TransitionShockCardController.cs
- Testing/Heroes/DriftTests.cs
> Drift's Transition Shock improvement

- CauldronMods/DeckLists/Hero/LadyOfTheWoodDeckList.json
> Lady of the Wood Base Flipped Icons

- CauldronMods/Controller/Heroes/Gyrosaur/CardSubClasses/GyrosaurUtilityCardController.cs
- CauldronMods/Controller/Heroes/Gyrosaur/Cards/RecklessAlienRacingTortoiseCardController.cs
- Testing/Heroes/GyrosaurTests.cs
Note that SelectFunctionDecisions do not allow for Custom Decision Text, so had to adjust all of the implementation to use SelectWordDecision
Closes #1234
> Gyro stabilizer decision improvement

- CauldronMods/Controller/Heroes/TangoOne/Cards/OneShotOneKillCardController.cs
> Improved Tango One's One Shot One Kill Special String

- CauldronMods/DeckLists/Hero/StarlightDeckList.json
Changes flips icons to be correct
Removes random extra opening lines
Closes #1282
> Starlight Decklist Fixes

- CauldronMods/Controller/Environments/OblaskCrater/Cards/IndustriousHulkCardController.cs
> Oblask Crater's Industrious Hulk Custom UI Decision

- CauldronMods/Controller/Heroes/Necro/CharacterCards/PastNecroCharacterCardController.cs
> 1929 Necro Incap 3 Custom UI Text

- CauldronMods/Controller/Heroes/Cypher/Cards/BackupPlanCardController.cs
- CauldronMods/Controller/Heroes/Cypher/Cards/CyborgBlasterCardController.cs
- CauldronMods/Controller/Heroes/Cypher/Cards/CyborgPunchCardController.cs
- CauldronMods/Controller/Heroes/Cypher/Cards/HeuristicAlgorithmCardController.cs
- CauldronMods/Controller/Heroes/Cypher/Cards/NeuralInterfaceCardController.cs
> Cypher UI decision improvements

- CauldronMods/DeckLists/Villain/MenagerieDeckList.json
- CauldronMods/DeckLists/Villain/ScreaMachineDeckList.json
> Text fixes

- CauldronMods/Controller/Heroes/Cricket/Cards/SonicAmplifierCardController.cs
- CauldronMods/Controller/Heroes/Echelon/CardSubClasses/InOutCardController.cs
- CauldronMods/Controller/Heroes/Echelon/Cards/FindAWayInCardController.cs
- CauldronMods/Controller/Heroes/Echelon/Cards/NeedAWayOutCardController.cs
- CauldronMods/Controller/Heroes/Echelon/Cards/SurpriseAttackCardController.cs
- CauldronMods/Controller/Villains/TheMistressOfFate/Cards/ChaosButterflyCardController.cs
Closes #1249 
Closes #1255 
Closes #1242 
Closes #1240
> UI custom decision texts

- CauldronMods/Controller/Heroes/Impact/CharacterCards/ImpactCharacterCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/ParticleColliderCardController.cs
> Damage preview improvements

- CauldronMods/Controller/Heroes/Starlight/CardSubClasses/StarlightCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/CardSubClasses/RoninAssignableCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/CardSubClasses/TheKnightCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/Cards/CatchYourBreathCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/Cards/ShortSwordCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/Cards/StalwartShieldCardController.cs
- Testing/Heroes/TheKnightTests.cs
> The Knight assigning equipment in OA mode

- CauldronMods/Controller/Heroes/Titan/Cards/ForbiddenArchivesCardController.cs
- Testing/Heroes/TitanTests.cs
When Titan is about to draw, he doesn't need to be asked Yes/No (unless an outside force would cause problems) as his draw does not impact the damage he takes.
Closes #1210
> Titan's Forbidden Archives Improvements

- CauldronMods/Controller/Environments/SuperstormAkela/Cards/RideTheCurrentsCardController.cs
- Testing/Environments/SuperstormAkelaTests.cs
> Ride The Currents looks only in its own battle zone now

- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftSubCharacterCardController.cs
- CauldronMods/Controller/Heroes/Quicksilver/CharacterCards/UncannyQuicksilverCharacterCardController.cs
- CauldronMods/Controller/Heroes/Titan/SubCardClasses/TitanBaseCharacterCardController.cs
> Power change compatibility update

- CauldronMods/DeckLists/Villain/DendronDeckList.json
> typo on Dendron

- CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/FallCardController.cs
- Testing/Heroes/LadyOfTheWoodTests.cs
Copied from Nitrogen Rounds
Closes #1309
> Lady of the Wood Fall reduce damage trigger order

- CauldronMods/Controller/Environments/CatchwaterHarbor/CardSubClasses/TransportCardController.cs
- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/AllAboardCardController.cs
- CauldronMods/Controller/Heroes/Echelon/Cards/TeslaKnucklesCardController.cs
- CauldronMods/Controller/Heroes/Echelon/CharacterCards/FutureEchelonCharacterCardController.cs
- CauldronMods/Controller/Villains/Dynamo/Cards/CatharticDemolitionCardController.cs
- CauldronMods/Controller/Villains/ScreaMachine/CardSubClasses/ScreaMachineBandCardController.cs
- CauldronMods/Controller/Villains/ScreaMachine/CardSubClasses/ScreaMachineBandCharacterCardController.cs
- CauldronMods/DeckLists/Environment/CatchwaterHarborDeckList.json
- CauldronMods/DeckLists/Villain/ScreaMachineDeckList.json
- Testing/BaseTest.cs
- Testing/Villains/ScreaMachineTests.cs
This should ideally be approved but not yet merged, in anticipation of the proper release of the new Sentinels version.
> Compatibility 2021 05 22

- CauldronMods/Controller/Heroes/LadyOfTheWood/CharacterCards/MinistryOfStrategicScienceLadyOfTheWoodCharacterCardController.cs
- Testing/Heroes/LadyOfTheWoodVariantTests.cs
This replaces PR #1345 with compatibility updates that have been made since then
> Moss lotw oblivaeon fix recreated

- CauldronMods/Controller/Environments/OblaskCrater/Cards/UnknownHerdsCardController.cs
- CauldronMods/Controller/Environments/WindmillCity/Cards/GrayPharmaceuticalBuildingCardController.cs
- CauldronMods/Controller/Heroes/Echelon/Cards/SurpriseAttackCardController.cs
- CauldronMods/Controller/Heroes/Gargoyle/Cards/BioenergyPulseCardController.cs
- CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/SnowshadeGownCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/ChromodynamicsCardController.cs
- CauldronMods/Controller/Heroes/Titan/Cards/VulcansJudgmentCardController.cs
- Testing/Environments/OblaskCraterTests.cs
- Testing/Environments/WindmillCityTests.cs
- Testing/Heroes/EchelonTests.cs
- Testing/Heroes/LadyOfTheWoodTests.cs
While this fixes the problems raised in #1225, I think that issue should remain open for now so Handelabra can reference it for potential future CardController/Void Belter changes.
> Power Source Contagion

- CauldronMods/DeckLists/Hero/BaccaratDeckList.json
> Removed Trailing space for title of Ace of Sorrows

- CauldronMods/Controller/Heroes/Drift/Shift Track/DualShiftTrackUtilityCardController.cs
- Testing/Heroes/DriftDualVariantTests.cs
Lots of red-blue needed to be cut out.
> Fix Dual Drift

- Testing/CauldronBaseTest.cs
- Testing/Environments/StSimeonsCatacombsTests.cs
- Testing/Random/BaccaratRandomTests.cs
- Testing/Random/CricketRandomTests.cs
- Testing/Random/CypherRandomTests.cs
- Testing/Random/DocHavocRandomTests.cs
- Testing/Random/DriftRandomTests.cs
- Testing/Random/EchelonRandomTests.cs
- Testing/Random/GargoyleRandomTests.cs
- Testing/RandomGameTest.cs
- Testing/Testing.csproj
- Testing/Villains/OutlanderTests.cs
- Testing/Villains/TheInfernalChoirTests.cs
- Testing/Villains/VectorTests.cs
Fixed a few flaky tests
Add the random test framework and an example using Drift
> Flaky Test Fixes + Random Test Framework

- CauldronMods/DeckLists/Villain/AnathemaDeckList.json
> fixed typo

- CauldronMods/DeckLists/Hero/NecroDeckList.json
> Cleaned up Text and Icons for Necro

- CauldronMods/DeckLists/Villain/AnathemaDeckList.json
- CauldronMods/DeckLists/Villain/DendronDeckList.json
- CauldronMods/DeckLists/Villain/GrayDeckList.json
- CauldronMods/DeckLists/Villain/OriphelDeckList.json
- CauldronMods/DeckLists/Villain/OutlanderDeckList.json
- CauldronMods/DeckLists/Villain/SwarmEaterDeckList.json
- CauldronMods/DeckLists/Villain/TheRamDeckList.json
- CauldronMods/DeckLists/Villain/TiamatDeckList.json
- CauldronMods/DeckLists/Villain/VectorDeckList.json
Closes #1417
Updates based on the latest community survey
> Difficulties Adjustments

- CauldronMods/Controller/Environments/NightloreCitadel/Cards/AethiumCannonCardController.cs
> Added Skip Button to Aethium Cannon's End of Turn Decision

- CauldronMods/Controller/Villains/Dynamo/Cards/CrimeSpreeCardController.cs
> Added Missing Card Source for Crime Spree

- CauldronMods/Controller/Environments/TheWanderingIsle/Cards/AmphibiousAssaultCardController.cs
> Added Missing Card Source for Amphibious Assault

- CauldronMods/DeckLists/Hero/MalichaeDeckList.json
> Added instead to Malichae's Djinn text to better match behavior

- CauldronMods/Controller/Environments/NightloreCitadel/Cards/WarpBridgeCardController.cs
- Testing/Environments/NightloreCitadelTests.cs
> Warp bridge should affect cards under cards

- CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/TemporalReversalCardController.cs
> Temporal Reversal Decision Improvement

- CauldronMods/Controller/Heroes/LadyOfTheWood/CharacterCards/MinistryOfStrategicScienceLadyOfTheWoodCharacterCardController.cs
- CauldronMods/DeckLists/Hero/LadyOfTheWoodDeckList.json
With the update to token pools from a few weeks ago, we can improve this implementation.
> MOSS Lady of the Wood token pool improvements

- CauldronMods/Controller/Heroes/Cricket/Cards/SwarmingFrequencyCardController.cs
- Testing/Heroes/CricketTests.cs
> Swarming frequency Special String

- CauldronMods/Controller/Environments/VaultFive/CardSubClasses/ArtifactCardController.cs
- CauldronMods/Controller/Environments/VaultFive/Cards/MapToLostChothCardController.cs
- Testing/Environments/VaultFiveTests.cs
> Vault Five Artifact Improvements when there are less than the expected number of active TurnTakers

- CauldronMods/Controller/Environments/BlackwoodForest/Cards/VengefulSpiritsCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
The overall discard is now optional, but if a player is discarding, they must discard 2 cards.
Closes #911
> Vengeful spirits improvement

- CauldronMods/Controller/Environments/VaultFive/CardSubClasses/ArtifactCardController.cs
> Improve Artifacts Choose Owner Decision Title

- CauldronMods/Controller/Heroes/Gargoyle/Cards/EssenceTheftCardController.cs
Closes #1390 
My code isn't letting me compile due to having an outdated solution I can't update, so no tests were ran on this yet.
> Made Essence Thief optional and removed unused lines

- CauldronMods/Controller/Heroes/LadyOfTheWood/CharacterCards/SeasonsOfChangeLadyOfTheWoodCharacterCardController.cs
- CauldronMods/Controller/Heroes/Necro/CharacterCards/PastNecroCharacterCardController.cs
Improved Custom UI Decisions for 1929 Necro and Seasons of Change Lady of the Wood
Closes #1398
> Lady of Wood and Necro Incap Custom UI Decisions

- CauldronMods/Controller/Heroes/TangoOne/Cards/WetWorkCardController.cs
- Testing/Heroes/TangoOneTests.cs
When Wet Work is played, Tango One can now choose the order of trashes to shuffle back into the deck. There is also a choose for me option on the decision.
Closes #1410
> Wet work Decision Improvements

- Art/Atlas/EndGameEnvironments0.json
> Fixed Environment End Game Atlas Naming

- Art/Atlas/BlackwoodForestAtlas0.json
- Art/Atlas/TheCybersphereAtlas0.json
- Testing/Art/ArtTestBase.cs
> Fixed Environment Micro Art Naming

- CauldronMods/Controller/Heroes/Vanish/Cards/TacticalRelocationCardController.cs
- Testing/Heroes/VanishTests.cs
Closes #1389
This was caused in two places. One that MigrantP pointed out with SelectTurnTakersDecision, as well as the SelectionType on WasDamagedSelection. I'm not sure if there is a SelectionType that would work, or be better, but I made a custom string to get it working at least.
> Tactical Relocation Yes/No message

- CauldronMods/Controller/Heroes/Terminus/Cards/UnusualSuspectsCardController.cs
- Testing/Heroes/TerminusTest.cs
> Unusual suspects - Aeon Men interaction

- CauldronMods/Controller/Villains/TheInfernalChoir/Cards/VagrantHeartPhase1CardController.cs
This is a UI/preview problem, so no new test is possible, but the old tests work.
Fixes #1400
> Infernal Choir double damage prevention

- CauldronMods/Controller/Heroes/Vanish/Cards/FlashReconCardController.cs
- Testing/Heroes/VanishTests.cs
> Flash Recon Skipping Aeon Men

- CauldronMods/Controller/Heroes/Malichae/CardSubClasses/DjinnOngoingController.cs
- CauldronMods/Controller/Heroes/Malichae/Cards/GrandBathielCardController.cs
- CauldronMods/Controller/Heroes/Malichae/Cards/GrandEzaelCardController.cs
- CauldronMods/Controller/Heroes/Malichae/Cards/GrandReshielCardController.cs
- CauldronMods/Controller/Heroes/Malichae/Cards/GrandSomaelCardController.cs
- CauldronMods/Controller/Heroes/Malichae/Cards/HighBathielCardController.cs
- CauldronMods/Controller/Heroes/Malichae/Cards/HighEzaelCardController.cs
- CauldronMods/Controller/Heroes/Malichae/Cards/HighReshielCardController.cs
- CauldronMods/Controller/Heroes/Malichae/Cards/HighSomaelCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/CherenkovDriveCardController.cs
- CauldronMods/DeckLists/Hero/MalichaeDeckList.json
- Testing/Heroes/PyreTests.cs
Implemented logic to hardcode interaction between cherenkov drive and djinn ongoings.
This is not ready for approval yet.
> Cherenkov drive and djinns

- CauldronMods/Controller/Heroes/Quicksilver/Cards/LiquidMetalCardController.cs
- Testing/Heroes/QuicksilverTests.cs
Also improves messaging when for unable-to-find
> Liquid Metal matching cards display

- CauldronMods/Controller/Heroes/Vanish/Cards/AbductAndAbandonController.cs
- Testing/Heroes/VanishTests.cs
> Abduct and abandon improvements

- CauldronMods/Controller/Heroes/Vanish/CharacterCards/TombOfThievesVanishCharacterCardController.cs
- Testing/Heroes/VanishVariantTests.cs
> Tomb of Thieves Vanish Power Responds Even When No Damage is Dealt

- CauldronMods/Controller/Environments/SuperstormAkela/CardSubClasses/SuperstormAkelaCardController.cs
- Testing/Environments/SuperstormAkelaTests.cs
> Improved Ride the Currents to update the UI as soon as the card is moved

- CauldronMods/Controller/Heroes/Gargoyle/Cards/ViolentAssistCardController.cs
Fixes #1397 
UI issue, so no test possible, but I have tried it in-game.
> Violent assist With Redirects

- CauldronMods/Controller/Environments/DungeonsOfTerror/CardSubClasses/DungeonsOfTerrorUtilityCardController.cs
- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/DelayedRockTrapCardController.cs
- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/MagicBladeCardController.cs
- Testing/Environments/DungeonsOfTerrorTests.cs
> Dungeons of terror Magic Blade battle zone check

- Art/Atlas/SwarmEaterAtlas0.json
Swapped Swarm Eater's front and back small art.
> Swarm Eater Small Art Fix

- CauldronMods/Controller/Villains/Celadroch/CharacterCards/CeladrochCharacterCardController.cs
- Testing/Villains/CeladrochTests.cs
> Celadroch Minion Summon Improvements

- CauldronMods/DeckLists/Environment/CatchwaterHarborDeckList.json
- CauldronMods/DeckLists/Environment/DungeonsOfTerrorDeckList.json
- CauldronMods/DeckLists/Environment/FSCContinuanceWandererDeckList.json
- CauldronMods/DeckLists/Environment/HalberdExperimentalResearchCenterDeckList.json
- CauldronMods/DeckLists/Environment/NightloreCitadelDeckList.json
- CauldronMods/DeckLists/Environment/NorthsparDeckList.json
- CauldronMods/DeckLists/Environment/OblaskCraterDeckList.json
- CauldronMods/DeckLists/Environment/StSimeonsCatacombsDeckList.json
- CauldronMods/DeckLists/Environment/SuperstormAkelaDeckList.json
- CauldronMods/DeckLists/Environment/TheCybersphereDeckList.json
- CauldronMods/DeckLists/Environment/VaultFiveDeckList.json
- CauldronMods/DeckLists/Hero/CricketDeckList.json
- CauldronMods/DeckLists/Hero/CypherDeckList.json
- CauldronMods/DeckLists/Hero/DocHavocDeckList.json
- CauldronMods/DeckLists/Hero/DriftDeckList.json
- CauldronMods/DeckLists/Hero/EchelonDeckList.json
- CauldronMods/DeckLists/Hero/GyrosaurDeckList.json
- CauldronMods/DeckLists/Hero/ImpactDeckList.json
- CauldronMods/DeckLists/Hero/LadyOfTheWoodDeckList.json
- CauldronMods/DeckLists/Hero/MagnificentMaraDeckList.json
- CauldronMods/DeckLists/Hero/MalichaeDeckList.json
- CauldronMods/DeckLists/Hero/NecroDeckList.json
- CauldronMods/DeckLists/Hero/QuicksilverDeckList.json
- CauldronMods/DeckLists/Hero/StarlightDeckList.json
- CauldronMods/DeckLists/Hero/TerminusDeckList.json
- CauldronMods/DeckLists/Hero/TheKnightDeckList.json
- CauldronMods/DeckLists/Hero/TheStrangerDeckList.json
- CauldronMods/DeckLists/Hero/TitanDeckList.json
- CauldronMods/DeckLists/Hero/VanishDeckList.json
- Testing/AssemblyTests.cs
Will also be going through the villain cards at some point, but I figured it would be nice to potentially have an update for the official release of the workshop and it wouldn't be worth holding these from release.
> Small-card Icon pass: environment and hero

- CauldronMods/Controller/Villains/Tiamat/Cards/HealingMagicCardController.cs
- Testing/Villains/TiamatHydraTests.cs
Closes #1528 
I had made a comment about checking Acid Breath and Sky Breaker, and both seem to be working fine. Added unit tests to prove it. :)
> Tiamat healing magic fix

- CauldronMods/Controller/Heroes/Pyre/CardSubClasses/PyreUtilityCardController.cs
- CauldronMods/Controller/Heroes/Pyre/CardSubClasses/PyreUtilityCharacterCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/AtomicPunchCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/CellularIrradiationCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/CherenkovDriveCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/FissionRegulatorCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/GammaBurstCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/IonTraceCardController.cs
- CauldronMods/Controller/Heroes/Pyre/CharacterCards/UnstablePyreCharacterCardController.cs
Not currently supported in-game, but ready to go for when it is.
> Pyre irradiate decision text

- CauldronMods/Controller/Villains/SwarmEater/Cards/NaniteCorruptionCardController.cs
> Change Damage Type of Swarm Eater's Nanite Corruption

- CauldronMods/Controller/Environments/DungeonsOfTerror/CardSubClasses/DungeonsOfTerrorUtilityCardController.cs
> Fix message prompt from Ring of Foresight

- CauldronMods/Controller/Villains/SwarmEater/CharacterCards/DistributedHivemindSwarmEaterCharacterCardController.cs
- Testing/Villains/SwarmEaterVariantTests.cs
> Hive mind swarm eater fix redirects

- CauldronMods/Controller/Heroes/Terminus/Cards/NoRestForTheWickedCardController.cs
- Testing/Heroes/TerminusTest.cs
> No rest for the wicked+ mmffcc

- CauldronMods/Controller/Environments/BlackwoodForest/Cards/DesolationCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
Closes #1511 
Closes #898 
Also adds custom decision text to make it clearer what is being asked of the player
> Blackwood Forest's Desolation Improvements

- CauldronMods/Controller/Villains/Celadroch/CardSubClasses/CeladrochPillarCardController.cs
Adjusts conditions of pillars to reduce the decisions that happen unless thresholds are actually crossed
Closes #1529
> Celadroch Pillars Timing Improvements

- CauldronMods/Controller/Villains/PhaseVillain/Cards/FrequencyShiftCardController.cs
- Testing/Villains/PhaseVillainTests.cs
> Frequency Shift Destroys Cards for Original Target

- CauldronMods/Controller/Heroes/Necro/CharacterCards/LastOfTheForgottenOrderNecroCharacterCardController.cs
> Last of the Forgetten Necro Incap 3 improvements

- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DualDriftSubCharacterCardController.cs
- Testing/CauldronBaseTest.cs
- Testing/Villains/TheMistressOfFateTests.cs
> Dual Drift loses shift track upon resurrection

- CauldronMods/Controller/Heroes/Cypher/CardSubClasses/CypherBaseCardController.cs
- CauldronMods/Controller/Heroes/Cypher/Cards/CyborgBlasterCardController.cs
- Testing/Heroes/CypherTests.cs
> Cypher and Isolated Hero

- CauldronMods/Controller/Heroes/Necro/CharacterCards/NecroCharacterCardController.cs
- CauldronMods/DeckLists/Hero/NecroDeckList.json
> Inclusive Language Cleanup

- CauldronMods/Controller/Villains/Mythos/CardSubClasses/MythosUtilityCardController.cs
- Testing/Villains/MythosTests.cs
> Mythos Advanced Applying on Only Back

- CauldronMods/Controller/Environments/StSimeonsCatacombs/CardSubClasses/StSimeonsGhostCardController.cs
- Testing/Environments/StSimeonsCatacombsTests.cs
> Ghosts Special Strings in OA

- CauldronMods/Controller/Villains/Outlander/Cards/DisarmingBlowCardController.cs
- Testing/Villains/OutlanderTests.cs
> Disarming Blow when Damage Dealt to One Hero

- CauldronMods/Controller/Heroes/Pyre/CardSubClasses/PyreUtilityCardController.cs
- CauldronMods/Controller/Heroes/Pyre/CardSubClasses/PyreUtilityCharacterCardController.cs
Pyre prompts were showing "Pyre is Pyre is deciding....". Removed the extra "Pyre is"
> Update Pyre Multiplayer Prompts

- CauldronMods/DeckLists/Hero/MagnificentMaraDeckList.json
> Add the limited keyword for Mystical Enhancement

- CauldronMods/Controller/Environments/OblaskCrater/Cards/IndustriousHulkCardController.cs
Small fixes to card sources and the like that were discovered through random game tests (mostly Guise related shenanigans).
> Random Test Fixes

- CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/SpringCardController.cs
- Testing/CauldronBaseTest.cs
- Testing/Heroes/LadyOfTheWoodTests.cs
- Testing/Heroes/LadyOfTheWoodVariantTests.cs
> Lady of the Wood's Spring heals even when no damage is dealt

- CauldronMods/Controller/Villains/Outlander/Cards/DisarmingBlowCardController.cs
For some reason, when the decision of who to discard cards first appears, the choose for me doesn't actually select the TurnTaker. This resolves the issue so that the discard effect actually happens.
Closes #1572
> Outlander's Disarming Blow Doesn't Work with Auto-Decide Discard

- CauldronMods/Controller/Heroes/Impact/Cards/HurledObstructionCardController.cs
- Testing/Heroes/ImpactTests.cs
> Hurled Obstruction Doesn't Exclude Heroic Infinitor

- CauldronMods/Controller/Heroes/Cricket/Cards/SonicAmplifierCardController.cs
- Testing/Heroes/CricketTests.cs
> Cards under Sonic Amplifier are now considered Not in Play

- CauldronMods/Controller/Environments/TheCybersphere/Cards/Gho5tCardController.cs
- Testing/Environments/TheCybersphereTests.cs
> Gho5t's Draw on Destruction was Non-Optional

- CauldronMods/Controller/Environments/BlackwoodForest/Cards/MirrorWraithCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
> Mirror Wraith Indestructibility Updates

- CauldronMods/Controller/Heroes/Quicksilver/Cards/IronRetortCardController.cs
- Testing/Heroes/QuicksilverTests.cs
> Iron Retort Timing Issues

- CauldronMods/Controller/Environments/SuperstormAkela/CardSubClasses/SuperstormAkelaCardController.cs
- CauldronMods/Controller/Environments/SuperstormAkela/Cards/ChurningVoidCardController.cs
- CauldronMods/Controller/Environments/SuperstormAkela/Cards/RideTheCurrentsCardController.cs
- Testing/Environments/SuperstormAkelaTests.cs
> Churning Void UI Update to Show Movement Immediately

- CauldronMods/Controller/Heroes/Pyre/CardSubClasses/PyreUtilityCharacterCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/IrradiatedMarkerCardController.cs
- Testing/Heroes/PyreTests.cs
Irradiated Cards now get a Special String to indicate that you may need to right click and select 'Play' to actually play it.
> Pyre's Irradiated Cards - Special String Improvement

- CauldronMods/DeckLists/Hero/MagnificentMaraDeckList.json
> Mara's Kalpak of Mysteries Text Fix

- CauldronMods/Controller/Environments/BlackwoodForest/Cards/TheBlackTreeCardController.cs
- CauldronMods/Controller/Environments/BlackwoodForest/Cards/WillOTheWispCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
> Will of the Wisps prevents The Black Tree Play

- CauldronMods/Controller/Heroes/Drift/CharacterCards/Dual/PastDriftCharacterCardController.cs
> Clean up 1929 drift prompts

- CauldronMods/Controller/Heroes/Quicksilver/Cards/IronRetortCardController.cs
- Testing/Heroes/QuicksilverTests.cs
Closes #1610 
When Guise uses Uh Yeah I'm That Guy! to copy Iron Retort, it prompts Quicksilver to play a card when it is destroyed. This PR fixes it so that Guise is prompted to play the card.
> Iron Retort's Play Still Affects Quicksilver when copied

- CauldronMods/Controller/Villains/PhaseVillain/Cards/InsubstantialMatadorCardController.cs
- Testing/Villains/PhaseVillainTests.cs
> Fix first clause of Insubstantial Matador being irreducible

- CauldronMods/Controller/Heroes/TheStranger/Cards/MarkOfBindingCardController.cs
- Testing/Heroes/TheStrangerTests.cs
> Fix mark of binding being able to go next to non-targets

- CauldronMods/Controller/Heroes/Drift/CharacterCards/AllInGoodTimeDriftCharacterCardController.cs
- Testing/BaseTest.cs
- Testing/Heroes/DriftVariantsTests.cs
> fixes to prevent one-shots from playing when no ongoings found

- CauldronMods/Controller/Heroes/Pyre/Cards/GammaBurstCardController.cs
- Testing/Heroes/PyreTests.cs
> Pyre's Gamma Burst and Heroic Infinitor

- Testing/Environments/CatchwaterHarborTests.cs
- Testing/Heroes/CricketTests.cs
- Testing/Heroes/GyrosaurTests.cs
there were flaky tests that based on the random seed would fail sometimes. I've controlled the variables more so they reliably pass
> fix flaky tests

- CauldronMods/Controller/Villains/Tiamat/CardSubClasses/TiamatSubCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/TiamatTurnTakerController.cs
- Testing/Villains/TiamatHydraTests.cs
> Move Tiamat's setup to StartGame

- CauldronMods/Controller/Heroes/MagnificentMara/Cards/AbracadabraCardController.cs
- Testing/Heroes/MagnificentMaraTests.cs
> Uh, Yeah, I'm That Guy! and Abracadabra! interaction fix

- CauldronMods/Controller/Heroes/Gargoyle/CardSubClasses/GargoyleUtilityCardController.cs
- Testing/Heroes/GargoyleTests.cs
> Fix Leech Field damage increase being persistent.

- CauldronMods/Controller/Heroes/Drift/CharacterCards/DriftTurnTakerController.cs
- CauldronMods/Controller/Heroes/Drift/Shift Track/DualShiftTrackUtilityCardController.cs
> Fixed Dual Drift special string conditions

- Testing/Environments/FSCContinuanceWandererTests.cs
- Testing/Environments/NightloreCitadelTests.cs
- Testing/Environments/StSimeonsCatacombsTests.cs
- Testing/Environments/SuperstormAkelaTests.cs
- Testing/Environments/TheCybersphereTests.cs
- Testing/Heroes/BaccaratTests.cs
- Testing/Heroes/CricketTests.cs
- Testing/Heroes/CricketVariantTests.cs
- Testing/Heroes/CypherVariantTests.cs
- Testing/Heroes/GyrosaurTests.cs
- Testing/Heroes/LadyOfTheWoodTests.cs
- Testing/Heroes/PyreVariantTests.cs
- Testing/Heroes/QuicksilverTests.cs
- Testing/Heroes/StarlightTests.cs
- Testing/Heroes/TangoOneTests.cs
- Testing/Heroes/VanishTests.cs
- Testing/Oblivaeon/Environments/WindmillCityTests.cs
- Testing/Villains/AnathemaVariantTests.cs
- Testing/Villains/CeladrochTests.cs
- Testing/Villains/DynamoTests.cs
- Testing/Villains/MenagerieTests.cs
- Testing/Villains/TheMistressOfFateTests.cs
Fix for 3 tests that would sometimes fail due to RNG:
TestAcceleratedEvolutionHeadIndestructibilityTest_FlippedVillainTurn_NegativeHP
TestReturnPulse1Target
TestPressureDrop_Destroy
Edit: I found more flaky tests
> Fix flaky tests 3/29/24

- CauldronMods/Controller/Heroes/Cricket/CharacterCards/RenegadeCricketCharacterCardController.cs
- Testing/Heroes/CricketVariantTests.cs
Fixes Renegade Cricket's power so that it can't play cards stolen by Dark Mind
> 1507 renegade cricket dark mind steals card cricket steals it back
