- Controller/Villains/Anathema/DopplegangerStrikeCardController.cs
- DeckLists/Villain/AnathemaDeckList.json
- Testing/Villains/AnathemaTests.cs
The card uses the spelling "Dopp**el**ganger" and that's what the decklist had in it.
> Fix spelling of doppelganger

- CauldronMods.csproj
Install the NUnit test adapter to run the tests directly using the VS 2019 Test running.
NOTE: To make this work I had to switch the target framework version. At some point we'll probably have to switch it back.
> Nunit test adapter

- Docs/CODE_OF_CONDUCT.md
- Docs/CODE_WISDOM.md
- Docs/CONTRIBUTING.md
- LICENSE
- README.md
Documentation update for discussion and review.
Added a Code of Conduct, shamelessly stolen from the Jorbs Slay the Spire Mod Github
Added a Constributing doc, again shamelessly stolen, but heavily edited
Added a License file (MIT) just so we have something.  The Jorb's mode uses the same, so it seemed a reasonable default.
Edited and cleaned up the ReadMe
> Documentation workshop

- Testing/Heroes/NecroTests.cs
Test would fail is the top two cards of the deck were Undead.  Card would correctly not Shuffle the deck.
Stacked Deck so that Shuffle Action always occurs.
> AdHoc-Necro Grand Summon Test Failure

- Controller/Villains/Anathema/Cards/BiofeedbackCardController.cs
- Testing/Villains/AnathemaTests.cs
test was destroying without a CardSource and Biofeedback did not have the nullcheck in the correct order
Adjusted test to add in the cardsoure
Adjusted Biofeedback to correctly do the nullcheck
> Ad-Hoc: Fixed Anathema failing test

- Docs/ADHOC_MOD_LOADING.md
- Docs/manifest.json
This branch contains a new md that explains how to adhoc load the mods (once implemented into Base SotM game).
This includes the manifest required for the game to find the decks.
> Adhoc mod loading

- Controller/Heroes/TangoOne/Cards/LineEmUpCardController.cs
Line Em Up was actually the problem card in described scenario as it's DestroyCardAction trigger wasn't checking for null on the ResponsibleCard property when fired.
In some cases (like Akash's Rejuv. Entropy) it's null.
Fixes crash issue #113
> Fixed issue 113

- Controller/Environments/BlackwoodForest/Cards/TheBlackTreeCardController.cs
Fixes issue #181 in which cards played from underneath The Black Tree don't behave like normal cards
> Fixes issue 181

- Testing/BaseTest.cs
AssertCannotPlayCards would fail by choosing a card that's already in play
> BaseTest bug fix

- Controller/Environments/TheWanderingIsle/Cards/IslandquakeCardController.cs
- Testing/Environments/TheWanderingIsleTests.cs
*Changes:*
* Add a QoL tooltip to Islandquake for hero targets that have healed Teryx.
* Grant the "immune to this damage" immunity as a persistent effect to fix most timing issues.
Partial #199 
*Limitations:*
"this damage" is identified using `CardSource`, which seems to mean "damage initiated by an effect on this card". There may be an edge case if a card that merges effects from multiple cards (similar to Guise's Uh Yeah I'm that Guy) is applied to environment cards.
The only other solution I could think of was passing a no-op `addStatusEffect` as a flag and doing an object identity check to find it in the ImmuneToDamageTrigger. Feels pretty hacky.
The Preemptive Payback test is ignored, because it doesn't work yet. It seems that the ImmuneToDamageTrigger has already determined it was …
> Partial Islandquake fixes

- Controller/Heroes/Baccarat/Cards/AfterlifeEuchreCardController.cs
- DeckLists/Hero/CricketDeckList.json
- DeckLists/Villain/GrayDeckList.json
- Testing/Heroes/BaccaratTests.cs
Closes #210 and #211 - The Gray Character Card flip now works
Closes #194 - Baccarat's Afterlife Euchre now only buffs his damage
> Bugfixes gray baccarat

- Controller/Villains/Dendron/Cards/MarkOfTheWrithingNightCardController.cs
Mark of the Writhing Night will now only target Hero Character cards
micro op on queries by storing TurnTaker
> issue #262 - Dendron - mark of Writhing targetting

- Controller/Villains/Anathema/Cards/AnathemaRampageCardController.cs
- Controller/Villains/Anathema/Cards/EnhancedSensesCardController.cs
- Controller/Villains/Gray/CharacterCards/GrayCharacterCardController.cs
While reviewing Owner.Deck references I found several cases where a Villain or Environment was dealing damage directly to Character car without checking for Multiple Character cards.
Added predicate call to FindCharacterCardToTakeDamage on Villain cards with hard coded calls to CharacterCard
> Multi CharacterCard Support Improvements

- Testing/Heroes/TheKnightTests.cs
Typo on closing the Values and setting expected HP by target type
> Fix the Knight's new plate helm/mail test

- Controller/Heroes/LadyOfTheWood/Cards/ThundergreyShawlCardController.cs
- Testing/Heroes/LadyOfTheWoodTests.cs
Thundergrey Shawl is supposed to do one "damage check" after other modifiers have been applied, and then retroactively make the damage irreducible if needed. Unfortunately this check happens after the reduce damage actions have *already* changed the DamageAmount,  so we need to go back through the ModifyDamageAction list adding back in all the damage that was taken away. This probably looks awkward as heck in the UI, but I can't think of a better way to do it.
> Lady Of The Woods Thundergrey Ordering

- Controller/Heroes/Necro/Cards/TaintedBloodCardController.cs
Previously, the trigger was tied to  the going to the End Phase, as that satisfies the criteria normally.
However if there is a card out that changes the turn order, such as Toppling Skyscraper in Superstorm Akela, this no longer was accurate. Changed to be tied to any phase change where the FromPhase was DrawCard
> Modified Tainted Blood Trigger Timing for Out of Order Phases

- Controller/Environments/BlackwoodForest/Cards/DenseBramblesCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
Instead of asking the player to enumerate the H-1 targets each time a possible member of that set is being damaged.
This makes the UI more consistent with how "the (single) target with the lowest HP is immune to damage" behaves, though the available decision text ("Is X the target with the lowest HP") isn't exactly correct.
Fixes #258 by assuming yes (like the helpers for single highest/lowest) in preview mode.
> Use a single Y/N when Dense Brambles is ambiguous

- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdEtherCardController.cs
- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdFoamcoreCardController.cs
- Testing/Environments/HalberdExperimentalResearchCenterTests.cs
Fixes #161
Also adds a special string, though for now it makes no attempt to suppress the "hero with the lowest HP" special string when a chemical trigger is in play. Not sure if that's possible without rewriting the special string.
> Add a Y/N prompt when Halberd 06 Foamcore is ambiguous

- Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalcyonCleanersCardController.cs
- Controller/Environments/Northspar/Cards/AethiumVeinCardController.cs
- Controller/ExtensionMethods.cs
- Controller/Heroes/LadyOfTheWood/Cards/LadyOfTheWoodsRebirthCardController.cs
- Controller/Heroes/TangoOne/Cards/LineEmUpCardController.cs
- Controller/Villains/Anathema/Cards/BiofeedbackCardController.cs
- Controller/Villains/Anathema/CharacterCards/AnathemaCharacterCardController.cs
- Controller/Villains/Gray/CharacterCards/GrayCharacterCardController.cs
- Testing/Environments/HalberdExperimentalResearchCenterTests.cs
- Testing/Environments/NorthsparTests.cs
- Testing/Heroes/LadyOfTheWoodTests.cs
- Testing/Villains/AnathemaTests.cs
- Testing/Villains/GrayTests.cs
Triggers based on Destroy Card Actions that have conditions base on the Card/TurnTaker that destroyed the card all need to have the conditions revised to support both Damage Based destruction and Destroy effect based destruction.  I ran into the problem first with TangoOne's LineEmUp, and this is the same basic issue.
The conditions are just complicated enough that my preferred solution is to add utility extension methods for the conditions, but I want to make sure everybody's comfortable with the solution before I apply it across a half dozen cards.
> General - DestroyCardAction extension methods and cleanup

- Controller/Heroes/Necro/CardSubClasses/UndeadCardController.cs
- Testing/Heroes/NecroTests.cs
Undead have HP set before they enter play to account for Enter's Play damage effects
> fix for issue #388

- Controller/Heroes/DocHavoc/CharacterCards/FirstResponseDocHavocCharacterCardController.cs
- Testing/Heroes/DocHavocPromoTests.cs
Damage was sourced from TurnTaker instead of Card, also made damage non-optional, as setting RequiredTargets to 0 and allowing the player to choose "stop dealing damage" is fine.
Fixes #439 and #433
> Fix Doc Havoc promo

- Controller/Heroes/Starlight/CharacterCards/StarlightCharacterCardController.cs
- Testing/Heroes/StarlightTests.cs
It needs to be able to block execution  when the player is choosing ambiguous lowest HP with AllowFastCoroutinesDuringPretend=false or similar, and that doesn't seem possible with status effects.
This is based on the proposed fix for Element of Lightning, though I clear the card property by defining a trigger on `ExpireStatusEffectAction`, so that it expires on status effect timing (status effects expire before normal "start of turn" triggers).
Also fix it ignoring damage from non-target sources (which should still be prevented if the "to the target with the lowest HP" side is triggered).
> Use a conditional Trigger for the damage prevention incap

- DeckLists/Villain/AnathemaDeckList.json
Heavy Carapace, Enhanced Senses, and Doppelganger Strike were all at 1 copy instead of 2
> Updated Anathema CardCounts

- Controller/Heroes/Quicksilver/Cards/MalleableArmorCardController.cs
- Testing/Heroes/QuicksilverTests.cs
The old version worked by setting Quicksilver's HP high enough to survive just before the blow hit, which ended up causing problems when it got redirected away from her at the last moment (she'd keep the boosted HP).
Now implemented by preventing the no-HP destruction and properly restoring her to 1HP.
> Proper implementation of Quicksilver's Malleable Armor

- Controller/Heroes/Baccarat/Cards/BringDownTheHouseCardController.cs
- Controller/Heroes/Baccarat/Cards/GraveyardBridgeCardController.cs
- Controller/Heroes/Baccarat/CharacterCards/BaccaratCharacterCardController.cs
- Controller/Heroes/Titan/Cards/ImmolateCardController.cs
- Controller/Villains/SwarmEater/Cards/HuntingGroundsCardController.cs
- Controller/Villains/SwarmEater/Cards/SubterranAugCardController.cs
- Controller/Villains/SwarmEater/CharacterCards/SwarmEaterCharacterCardController.cs
- DeckLists/Hero/BaccaratDeckList.json
- DeckLists/Villain/SwarmEaterDeckList.json
Fixes for
- Swarm Eater
#453 - Subterran Aug not always reducing damage - not sure about this being a perfect fix
#450 - Flipped Swarm Eater no longer deals damage on cards "Put Into Play" only on "Play"
#449 - Character Card typo addressed
#447 - Hunting Grounds now only triggers if the target was actually destroyed
Decklist Icons updated
- Titan
#444 - Weird graphics around Immolate
- Baccarat
#436 - Bring Down the House should no longer keep asking Yes/No destroy a card and will instead just allow a skip
#377 - Typo on Ace in the Hole addressed
Character card now says "Trick Cards" not "Cards Cards" on the special string
Graveyard Bridge now has a Special String with all trashed cards
> Varied fixes 12-8

- Controller/Heroes/Starlight/CharacterCards/StarlightTurnTakerController.cs
- Controller/Heroes/TheKnight/CharacterCards/TheKnightTurnTakerController.cs
- Controller/Villains/TheRam/CharacterCards/PastTheRamCharacterCardController.cs
- Controller/Villains/TheRam/CharacterCards/TheRamCharacterCardController.cs
- Controller/Villains/TheRam/CharacterCards/TheRamTurnTakerController.cs
- Controller/Villains/Tiamat/CardSubClasses/HydraTiamatInstructionsCardController.cs
- Controller/Villains/Tiamat/Cards/ElementalFrenzyCardController.cs
- Controller/Villains/Tiamat/CharacterCards/ElementalHydra/HydraWinterTiamatCharacterCardController.cs
- Controller/Villains/Tiamat/CharacterCards/ElementalHydra/Instructions/HydraFrigidEarthTiamatInstructionsCardController.cs
- Controller/Villains/Tiamat/CharacterCards/ElementalHydra/Instructions/HydraNoxiousFireTiamatInstructionsCardController.cs
- Controller/Villains/Tiamat/CharacterCards/ElementalHydra/Instructions/HydraThunderousGaleTiamatInstructionsCardController.cs
- Controller/Villains/Tiamat/CharacterCards/TiamatTurnTakerController.cs
- Controller/Villains/Tiamat/CharacterCards/WinterTiamatCharacterCardController.cs
- DeckLists/Hero/StarlightDeckList.json
- DeckLists/Villain/TheRamDeckList.json
- Testing/Heroes/StarlightVariantTests.cs
Correct ordering of Nightlore Council Starlight portraits
Tiamat and 1929 Ram use the "sneaking cards in early" method so their portraits load at start of game.
Fix some issues with Hydra Tiamat related to reloads
> Multi-Character Promo Improvements

- Controller/Heroes/Cypher/CharacterCards/SwarmingProtocolCypherCharacterCardController.cs
Previously, it was allowing a facedown card next to the instructions card. The select hero character card was not filtering on non-real cards, which was allowing that choice. Added to criteria
> Swarming Protocol Cypher fix

- CauldronMods/Controller/Heroes/Impact/CharacterCards/ImpactCharacterCardController.cs
When there aren't any ongoings in play, it was trying to remove a null trigger
> Fix null reference error in Impact's base power

- CauldronMods/Controller/Villains/Gray/Cards/UnwittingHenchmenCardController.cs
- Testing/Villains/GrayTests.cs
Also tightens up some edge cases where there exists an equipment but for whatever reason it doesn't get destroyed - indestructibility, replacement effects, etc.
Fixes #729
> Null reference check in Unwitting Henchmen

- CauldronMods/Controller/Heroes/Necro/CardSubClasses/NecroCardController.cs
Similar to artifacts in Vault5, rewinds caused a game crash when playing certain cards with the power on 1929 necro active. Adding null checks seems to have resolved problems, although i don't have a super dependable way to test it
> 1929 Necro Rewind Crashes

- CauldronMods/Controller/Heroes/Titan/Cards/StubbornGoliathCardController.cs
Stubborn Goliath uses DealDamage's 'addStatusEffect' parameter
Also can select targets even if he can't deal damage.
Restrict targets to non-heroes
> Improve Stubborn Goliath

- CauldronMods/Controller/Heroes/Drift/Shift Track/DualShiftTrackUtilityCardController.cs
- CauldronMods/Controller/Heroes/Drift/Shift Track/ShiftTrackUtilityCardController.cs
- Testing/Heroes/DriftTests.cs
The Shift Track flips when Drift does, so its "Card.IsIncapacitated" returns true and the game recognizes that all heroes have been defeated.
> Fix Drift incapacitation

- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftBaseCardController.cs
- CauldronMods/Controller/Heroes/Drift/Cards/MakeEverySecondCountCardController.cs
- CauldronMods/Controller/Heroes/Drift/Cards/TransitionShockCardController.cs
- Testing/Heroes/DriftTests.cs
Formerly they were going off if *any* token pool was modified to the proper amount.
> Restrict Drift's on-shift triggers to her own shifting

- CauldronMods/Controller/Environments/WindmillCity/Cards/CrackedWaterMainCardController.cs
- CauldronMods/DeckLists/Environment/WindmillCityDeckList.json
- Testing/Environments/WindmillCityTests.cs
Damage dealt to responders is cold.
Reduces damage dealt *by* rather than *to* non-environment cards.
> Fix Cracked Water Main

- CauldronMods/Controller/Villains/PhaseVillain/CharacterCards/PhaseVillainCharacterCardController.cs
- Testing/Villains/PhaseVillainTests.cs
No longer removes nemesis triggers
Does not have the damage boost on the back side if the immediate flip effect causes her to do damage.
> Improve Phase flip slightly

- Testing/Heroes/TangoOnePromoTests.cs
Closes #644 
I created a test that added in Save and Loading to 1929 Tango One power, and it goes off without a hitch. 
Closing the PR as cannot replicate but I figure the added lines into the test code is worth having, hence this PR
> Fix for #644 (kinda) - 1929 Tango One

- CauldronMods/Controller/Heroes/Impact/Cards/LocalMicrogravityCardController.cs
Added a check to make sure the game is started before evaluating who the active turn taker is. Fixes a null exception.
> Add check for game start

- CauldronMods/Controller/Villains/Dynamo/Cards/PythonCardController.cs
- Testing/Villains/DynamoTests.cs
Python's reduce damage effect wasn't really once per turn
Reduce damage effect was occurring for instances of 0 damage
> Python issues

- CauldronMods/Controller/Heroes/Titan/Cards/StubbornGoliathCardController.cs
stubborn goliath's redirection status effect while strictly doesn't expire when titan is destroyed, doesn't make sense, as you can't redirect that damage to Titan anymore
Closes #984
> fix for #984 - stubborn goliath status effect

- CauldronMods/DeckLists/Hero/DriftDeckList.json
> added missing promo title for dual drift

- CauldronMods/Controller/Villains/Tiamat/CardSubClasses/TiamatSubCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/Cards/ElementOfLightningCardController.cs
- Testing/Villains/TiamatHydraTests.cs
- Testing/Villains/TiamatTests.cs
Closes #982 
Previously, Element of Lightning kept track of who isn't allowed to draw by character card, but that doesn't work for multi characters or if Completionist Guise swaps out the character card.
Changed the implementation to go based on the TurnTaker instead
> Tiamat element of lightning fixes

- CauldronMods/Controller/Heroes/Quicksilver/CardSubClasses/QuicksilverBaseCardController.cs
- CauldronMods/Controller/Heroes/Quicksilver/Cards/LiquidMetalCardController.cs
- Testing/Heroes/QuicksilverTests.cs
If there are no more combos in hand, the "Deal self damage to play a combo" now explicitly calls out "Deal self damage to no effect"
> Quicksilver combo improvements

- CauldronMods/Controller/Heroes/TheKnight/CardSubClasses/RoninAssignableCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/CardSubClasses/TheKnightCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/CardSubClasses/TheKnightUtilityCharacterCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/CharacterCards/WastelandRoninTheKnightCharacterCardController.cs
- Testing/CauldronBaseTest.cs
- Testing/Heroes/TheKnightTests.cs
- Testing/Heroes/TheKnightVariantTests.cs
Fixes to the following situations:
*A non-Ronin Knight is brought in to a replace another hero. His one-shots should not ask for who to deal the damage
*A non-Ronin Knight is brought in to replace Ronin Knights. Ronin Knights should not be revived and put back into play.
*A non-Knight hero is brought in to replace a Knight character. None of the StartOfGame Knight triggers should fire
> The knight and oblivaeon

- CauldronMods/Controller/Heroes/Starlight/CardSubClasses/StarlightSubCharacterCardController.cs
- CauldronMods/Controller/Heroes/Starlight/CharacterCards/NightloreCouncilStarlightCharacterCardController.cs
- Testing/CauldronBaseTest.cs
- Testing/Heroes/StarlightTests.cs
- Testing/Heroes/StarlightVariantTests.cs
Fixes to the following situations:
*A non-Nightlore Council Starlight is brought in to a replace another hero. Her one-shots should not ask for who to deal the damage
*A non-Nightlore Council Starlight is brought in to replace Nightlore Council Starlight.  Nightlore Council Starlight should not be revived and put back into play.
*A non-Starlight hero is brought in to replace a Starlight character. None of the StartOfGame Starlight triggers should fire
> Starlight and oblivaeon

- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/RestfulInnCardController.cs
- Testing/Environments/DungeonsOfTerrorTests.cs
This also affects any hero in oblivaeon with incapped heroes in their play area
Closes #1032
> Fix for 1032 - restful inn with multiple character cards

- CauldronMods/Controller/Villains/Vector/CharacterCards/VectorTurnTakerController.cs
Closes #1042 
The SetHP call in the TurnTaker was missing a CardSource
> Fix for 1042 - Vector Game Freezes on Start in Multiplayer

- CauldronMods/Controller/Heroes/Titan/Cards/ReversalCardController.cs
- Testing/Heroes/TitanTests.cs
Titan's redirection status effect was not being added if Titan can't deal damage.
Passed parameter to allow for selection of target to happen regardless
> Titan's Reversal When Cannot Deal Damage

- CauldronMods/Controller/Heroes/Terminus/Cards/FlashBeforeYourEyesCardController.cs
- Testing/Heroes/TerminusTest.cs
Flash Before Your Eyes would try to show the number of cards in trashes that weren't real (like the "First Battlezone's Scion's Trash")
Also added fix to only show within its own battlezone
> Flash before your eyes special string fix

- CauldronMods/Controller/Heroes/Pyre/CardSubClasses/PyreUtilityCharacterCardController.cs
- CauldronMods/Controller/Heroes/Pyre/CharacterCards/PyreTurnTakerController.cs
- Testing/Heroes/PyreTests.cs
The IrradiatedCard marker was getting confused on the new TurnTaker coming in. Added OverrideTurnTaker card property to fix the issue
> Softlock when Pyre Incaps in Oblivaeon mode

- CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/HeartOfTheWandererCardController.cs
- CauldronMods/Controller/Heroes/Cricket/Cards/EchonavigationCardController.cs
- CauldronMods/Controller/Heroes/Vanish/Cards/FlashReconCardController.cs
- CauldronMods/Controller/Heroes/Vanish/Cards/TacticalRelocationCardController.cs
- Testing/Environments/FSCContinuanceWandererTests.cs
- Testing/Heroes/CricketTests.cs
- Testing/Heroes/VanishTests.cs
Cards that reveal from all decks should reveal from subdecks, but only real ones (not mission deck or fake scion turntaker decks)
Modified: Flash Recon, Echonavigation, Heart of the Wanderer
Closes #1029 
Closes #928
> Reveal from all decks Oblivaeon

- CauldronMods/Controller/Heroes/Cricket/Cards/GrasshopperKickCardController.cs
- Testing/Heroes/CricketTests.cs
Enraged Terror Bird counts as an environment target, but not as environment, so it was not being picked up by the status effect criteria for what to be immune to. Re-implemented to use a trigger and card property instead. Also added special strings and messaging to mimic a normal status effect behavior.
Closes #1113
> Fix for 1113: Grasshopper kick and enraged terror bird

- CauldronMods/Controller/Villains/PhaseVillain/Cards/ResidualDesynchronizationCardController.cs
- Testing/Villains/PhaseVillainTests.cs
This is not strictly necessary as the damage fizzles since the obstacle is out of play and won't deal damage but its more of a QoL fix so it doesn't cause the players confusion
> Phase residual desynchronization and Destroyed Obstacles

- CauldronMods/Controller/Villains/ScreaMachine/CharacterCards/SliceCharacterCardController.cs
- Testing/Villains/ScreaMachineTests.cs
Slice's ultimate end of turn effect was missing null checks for if there was a hero target with the second lowest HP (ie only one hero left)
> Slice ultimate freeze fix

- CauldronMods/Controller/Environments/CatchwaterHarbor/Cards/AbandonedFactoryCardController.cs
- CauldronMods/Controller/Environments/DungeonsOfTerror/Cards/TheresAlwaysABardCardController.cs
- CauldronMods/Controller/Heroes/Cypher/Cards/BackupPlanCardController.cs
- CauldronMods/Controller/Heroes/DocHavoc/Cards/ImprovisedMineCardController.cs
- CauldronMods/Controller/Heroes/Gargoyle/Cards/YourStrengthIsMineCardController.cs
Closes #1213 
This affected a few other cards as well. It looks like SelectionType.DestroySelf was not presenting the proper prompt, whereas SelectionType.DestroyCard was
> Changed DestroySelf to DestroyCard to get proper text prompt

- CauldronMods/Controller/Heroes/Echelon/Cards/OverwatchCardController.cs
- CauldronMods/Controller/Heroes/MagnificentMara/Cards/DowsingCrystalCardController.cs
- Testing/Heroes/EchelonTests.cs
- Testing/Heroes/MagnificentMaraTests.cs
Overwatch wouldn't deal its damage at all if the card had been destroyed.
Dowsing Crystal had an odd bug where, if you blew it up for the damage boost, it would have enough permission to deal damage but not enough permission to remove the "targetable" status on things like Ennead Demigods.
> Fix Mara and Echelon status-effect damage issues

- CauldronMods/Controller/Heroes/Starlight/CardSubClasses/MultiStarlightIndividualCardController.cs
- CauldronMods/Controller/Heroes/Starlight/CharacterCards/StarlightOfAsheronCharacterCardController.cs
- CauldronMods/Controller/Heroes/Starlight/CharacterCards/StarlightOfCryosFourCharacterCardController.cs
- CauldronMods/Controller/Heroes/Starlight/CharacterCards/StarlightOfTerraCharacterCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/CardSubClasses/MultiKnightIndividualCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/CharacterCards/TheOldKnightCharacterCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/CharacterCards/TheYoungKnightCharacterCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/CharacterCards/WastelandRoninTheKnightCharacterCardController.cs
- Testing/Villains/TheMistressOfFateTests.cs
Ronin Knights and Nightlore Starlight caused all their cards to be removed from the game twice, resulting in the preservation by Mistress of Fate not working. Created new subclass based on the Sentinels to resolve issue
Closes #1202
> Mistress of fate + Ronin Knights/Nightlore Starlight

- CauldronMods/Controller/Heroes/Terminus/Cards/RailwaySpikeCardController.cs
Presents a "Remove 3 tokens to no effect" message when damage source is a non-target.
Cleaned up code.
Closes #1274
> Terminus' Railway Spike Improvements

- CauldronMods/Controller/Environments/BlackwoodForest/Cards/VengefulSpiritsCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
The Special String on Vengeful Spirits was erroring out. Made it safe by collecting list of all trashes and adding for each one. That way if there is none, nothing happens and if multiple multiple get added
Closes #1251
> Blackwood forest not loading in oa

- CauldronMods/Controller/Heroes/Malichae/Cards/ZephaerensCompassCardController.cs
- Testing/Heroes/MalichaeTests.cs
Changed criteria to look for all djinns, not just the ones in Malichae's play area.
> Malichae's Zephaeren's Compass Ignores Chasm's Djinns

- CauldronMods/Controller/Environments/OblaskCrater/Cards/InvasiveGrowthCardController.cs
The StatusEffect making environment cards indestructible included the card being destroyed. Corrected this. No new test case, as existing TestInvasiveGrowthEnviromentTargetDestroyed test was failing
Closes #1266
> Oblask Crater's Invasive Growth Bug Fix

- CauldronMods/Controller/Heroes/TangoOne/Cards/WetWorkCardController.cs
- Testing/Heroes/TangoOneTests.cs
While it was allowing you to choose subdecks and shuffling subdecks, it was returning to the main TurnTaker.Deck instead of the appropriate subdeck location.
Closes #1278
> Tango One's Wetwork Bug Fix in Oblivaeon

- CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/HeartOfTheWandererCardController.cs
- Testing/Environments/FSCContinuanceWandererTests.cs
While it was choosing every subdeck, it was always revealing the card from the main deck and the trash option was only for the main deck.
Closes #1277
> FSC Continuance Wanderer's Heart of Wanderer Bug Fixes in Oblivaeon

- CauldronMods/Controller/Heroes/Vanish/Cards/FlashReconCardController.cs
- Testing/Heroes/VanishTests.cs
While the revealed cards were able to look at subdecks, the play card was not.
Note about some current behavior: the OA subdecks (Aeon Men Deck and Scion Deck) only become "visible" if there is a target in play in the same battlezone as the card itself (in this case, forewarned). This is why we play and aeon man and scion at the start of the test.
Closes #1273
> Vanish's Forewarned Bug Fixes in Oblivaeon

- CauldronMods/Controller/Heroes/Terminus/Cards/UnusualSuspectsCardController.cs
- Testing/Heroes/TerminusTest.cs
When checking if a card with a matching keyword existed in any trash, it was not checking sub trashes.
Closes #1272
> Terminus' Unusual suspects Bug Fix in Oblivaeon

- CauldronMods/Controller/Villains/Tiamat/Cards/ElementalFormCardController.cs
Player would get 2 messages when triggering Elemental Form:
"Tiamat, The Mouth of the Inferno is immune to Projectile damage."
"Tiamat used Elemental Form to become immune to Projectile damage. "
Consolidated into one message that will look like:
"Tiamat, The Mouth of the Inferno used Elemental Form to become immune to Projectile damage. "
Closes #1291
> Tiamat's Elemental Form Improvement

- CauldronMods/Controller/Villains/Gray/CharacterCards/GrayCharacterCardController.cs
- Testing/CauldronBaseTest.cs
- Testing/Villains/GrayTests.cs
Gray's Start of Turn flipped effect was continuously trying to destroy all ongoing/equipment cards until there are 2 left. When everything is indestructible, that becomes impossible. Allowed a backdoor if everything is indestructible.
Closes #1303
> Gray's Start of Turn Flipped Destruction and Fixed Point

- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftSubCharacterCardController.cs
- CauldronMods/Controller/Heroes/Titan/SubCardClasses/TitanBaseCharacterCardController.cs
- Testing/Heroes/DriftDualVariantTests.cs
- Testing/Heroes/DriftTests.cs
- Testing/Heroes/TitanTests.cs
When Titan or Drift was in the game and become incapped with no other heroes below 10 HP, Progeny starts an infinite loop of flipping back and forth. Added more support for incapping the off to the side cards.
Closes #1308
> Progeny and Titan/Drift

- CauldronMods/Controller/Environments/BlackwoodForest/Cards/TheBlackTreeCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
The Black Tree was coded to steal cards from every deck and subdeck, regardless of whether it was a real deck or not and whether that deck is visible to the environment.
Closes #1425
> The Black Tree and OblivAeon

- CauldronMods/Controller/Heroes/Cypher/Cards/RebuiltToSucceedCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/Cards/ArmYourselfCardController.cs
Closes #1376 
Per MigrantP, when selecting between locations, the Play Area should always be first.
Searched through the entire project and these were the only two that had play area + other locations with the play area not first
> Reorder play area move card destinations

- CauldronMods/Controller/Heroes/Necro/CardSubClasses/NecroCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/AbominationCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/BloodRiteCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/CorpseExplosionCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/GhoulCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/HellfireCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/NecroZombieCardController.cs
- CauldronMods/Controller/Heroes/Necro/Cards/PossessedCorpseCardController.cs
- Testing/Heroes/NecroTests.cs
- Testing/Heroes/NecroVariantTests.cs
There are some cards (notably "Red Menace" as an example) that are villain targets but not villain cards. The way Necro's cards were coded, it wouldn't hit these cards when they were supposed to.
Tested for both normal and 1929 flipped and "Red Menace" is affected in both situations appropriately.
Closes #1377
> Improve Necro's cards to Accomodate IsVillainTarget

- CauldronMods/Controller/Environments/VaultFive/Cards/SigQuilsSignCardController.cs
Previously, this said "Increase damage dealt by 1" for both status effects.
Now it says "Increase damage dealt to targets from {owner}'s deck by 1" and "Increase damage dealt by targets from {owner}'s deck by 1"
> Improved Sig Quil's Sign Status Effect Messaging

- CauldronMods/Controller/Environments/BlackwoodForest/Cards/MirrorWraithCardController.cs
- Testing/Environments/BlackwoodForestTests.cs
Closes #1406 
The effects when copying a mission work as intended, but the card text and keywords that were copied always copy the front side. Changed that to match whatever the state is, and added test to verify functionality
> Mirror Wraith and Mission Cards

- CauldronMods/Controller/Villains/Dynamo/CharacterCards/DynamoTurnTakerController.cs
- Testing/Villains/DynamoTests.cs
Closes #1411 
There's a poor interaction between Dynamo Challenge and Advanced that can cause Python/Copperhead to not be put into play at the start of the game if they are both stacked next to each other in the deck. This changes the function call to be played from anywhere, not just from deck.
> Dynamo Ultimate Interaction

- CauldronMods/Controller/Heroes/Impact/CharacterCards/ImpactCharacterCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/ParticleColliderCardController.cs
- Testing/Heroes/ImpactTests.cs
Impact's innate power does nothing when he has a "prevent the next damage" effect on him, as from Citizen Hammer and Anvil's Scorching Snap, which it should be able to clear. This fixes that, as well as improving its messaging around complete inabilities to deal damage.
Also applies to Pyre's Particle Collider.
> Impact innate power with prevent-next-damage effect

- CauldronMods/Controller/Heroes/Starlight/Cards/NightloreArmorCardController.cs
- Testing/Heroes/StarlightTests.cs
Closes #1117 
Nightlore Armor was double prompting when there is a live redirection trigger such as Lead From the Front. By doing self tracking we can make it so it only prompts once.
We do additionally tracking when we say no to the prompt to make sure it doesn't reprompt in future cases for that instance but does reprompt if its been redirected to a new target
This is a UI only change so there is no unit test case
> Nightlore Armor + Redirection Fix

- CauldronMods/Controller/Heroes/Terminus/Cards/GravenShellCardController.cs
- Testing/Heroes/TerminusTest.cs
Graven Shell's on DestroyCardAction trigger was looking for the card that destroyed the other card without first doing a null check to make sure it existed in the first place.
Closes #1479
Closes #1478
> Graven Shell Null Reference Issue

- CauldronMods/Controller/Heroes/MagnificentMara/Cards/WandOfBanishmentCardController.cs
- Testing/Heroes/MagnificentMaraTests.cs
Improved interaction with cards that have a null NativeDeck, such as Mission Cards.
Copied this fix from Warp Bridge.
Closes #1461
> Wand of Banishment and Mission Cards

- CauldronMods/Controller/Villains/ScreaMachine/Cards/MentalLinkCardController.cs
- Testing/Villains/ScreaMachineTests.cs
When the deck is empty, Mental Link should force a reshuffle and then play the top card, like the base game implementation of PlayTopCard
> Mental Link Improvement

- CauldronMods/Controller/Environments/StSimeonsCatacombs/Cards/LabyrinthGuideCardController.cs
- Testing/Environments/StSimeonsCatacombsTests.cs
When there are no heroes visible to Labyrinth Guide (either Mistress of Fate or OblivAeon battlezones) Labyrinth Guide was throwing a NullReferenceException. Added a short circuit and a message for that case.
> Labyrinth Guide Improvements

- CauldronMods/Controller/Villains/Anathema/CardSubClasses/AnathemaCardController.cs
- CauldronMods/Controller/Villains/Anathema/CardSubClasses/ArmCardController.cs
- CauldronMods/Controller/Villains/Anathema/CardSubClasses/BodyCardController.cs
- CauldronMods/Controller/Villains/Anathema/CardSubClasses/HeadCardController.cs
Closes #1549
Reduces the number of prompts a player sees when heads/arms/bodies are indestructible and entering play.
> Accelerated Evolution Anathema Indestructibility UI Improvements

- CauldronMods/Controller/Heroes/Quicksilver/CharacterCards/RenegadeQuicksilverCharacterCardController.cs
- Testing/Heroes/QuicksilverVariantsTests.cs
Renegade Quicksilver's second incap was firing even if no damage was actually dealt to a hero. Added the criteria in the status effect for the damage to be greater than 0 to fire
> Renegade Quicksilver Incap 2 - Only when damage is dealt

- CauldronMods/Controller/Villains/Vector/Cards/AnticoagulantCardController.cs
- Testing/Villains/VectorTests.cs
Changes damage to be dealt after Anticoagulant is destroyed rather than when it is destroyed, preventing infinite loops.
Closes #1568
> Anticoagulant Infinite Loop

- CauldronMods/Controller/Villains/TheInfernalChoir/Cards/VagrantHeartPhase1CardController.cs
- Testing/Villains/TheInfernalChoirTests.cs
When Drift has Vagrant Heart and dies, the game doesn't end, instead, The Infernal Choir just flips. This fixes that.
> Infernal Choir and Drift Fix

- CauldronMods/Controller/Heroes/Terminus/Cards/BoneChillingTouchCardController.cs
- Testing/Heroes/TerminusTest.cs
Closes #1567 
Bone Chilling Touch now only moves next to targets that are still in play after the dealt damage. Also, it now interacts better with Guise.
> Terminus' Bone Chilling Touch Improvements

- CauldronMods/Controller/Heroes/DocHavoc/Cards/ImmediateEvacCardController.cs
- Testing/Heroes/DocHavocTests.cs
Closes #1594 
Immediate Evacuation was looking up the character card for the hero discarding cards, which ran into a null issue with the Sentinels. Reworked the functions to not require character card and instead use the Hero Turn Taker
> Doc Havoc's Immediate Evacuation and Sentinels

- CauldronMods/Controller/Environments/TheChasmOfAThousandNights/Cards/BeyondTheVeilCardController.cs
- Testing/Environments/TheChasmOfAThousandNightsTests.cs
Beyond the Veil was not triggering for all instances of discarded cards, such as Chronological Sweetspot.
This fixes it by using MoveCardAction and checking for isDiscard instead of a DiscardCardAction
> Beyond the Veil Discard Trigger Fix

- CauldronMods/Controller/Villains/Celadroch/Cards/NightUnderTheMountainCardController.cs
- Testing/Villains/CeladrochTests.cs
If Night Under the Mountain is destroyed on Celadroch's turn, it's buff lasts through until the end of his next turn. This changes it just to be the end of his turn.
Closes #1609
> Night Under the Mountain's Buff on Destruction Stays Around for Too Long

- CauldronMods/Controller/Villains/ScreaMachine/CardSubClasses/ScreaMachineBandCharacterCardController.cs
- CauldronMods/Controller/Villains/ScreaMachine/CharacterCards/TheSetListCardController.cs
- Testing/Villains/ScreaMachineTests.cs
Closes #1499 
When a band member was destroyed with Sky Deck out, the band member would go under the villain deck. This fixes it so when the band member is destroyed they will always go straight to Removed From the Game
> ScreaMachine Band Members Can Be Affected by Sky Deck

- CauldronMods/Controller/Villains/Celadroch/CardSubClasses/CeladrochCelestialCardController.cs
- Testing/Villains/CeladrochTests.cs
Closes #773 
If damage is dealt to one of Celadroch's celestials, other triggers based on that damage could occur before the immunity is switched / cleared, resulting in both of the celestials having immunity.
> Celestials Triggers Can Be Interrupted for Joint Immunity

- CauldronMods/Controller/Villains/Tiamat/CardSubClasses/HydraTiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CardSubClasses/TiamatCharacterCardController.cs
Tiamat's heads construct a FlipCardAction directly; they don't need to and should just call GameController.FlipCard. This is a contributing factor for the recent Tiamat-doesn't-flip bug; Handelabra changed the FlipCardAction constructor so we get an exception when we try to call the old one. Pushing a new release of the mod will fix that bug, but this fix seemed worthwhile to do as well.
Superstorm Akela changes properties of the FlipCardAction that the helper method doesn't expose, so that's left the same.
All Tiamat tests still pass.
> Use GameController.FlipCard for Tiamat

- CauldronMods/DeckLists/Hero/DriftDeckList.json
- Testing/Heroes/DriftDualVariantTests.cs
SwitchCardsAction as of version 4 attempts to make unflipped hero character cards targets, with HP from the card definition:
```csharp
if (FirstCard.IsHeroCharacterCard && FirstCard.IsInPlayAndNotUnderCard && !FirstCard.IsTarget && !FirstCard.IsFlipped)
{
int value = FirstCard.Definition.HitPoints.Value;
IEnumerator coroutine = base.GameController.MakeTargettable(FirstCard, value, value, base.CardSource);
if (base.UseUnityCoroutines)
{
yield return base.GameController.StartCoroutine(coroutine);
}
else
{
base.GameController.ExhaustCoroutine(coroutine);
}
}
```
This is breaking Drift; when the shift track is switched this bit of code crashes because Definition.HitPoints is null.
MigrantP on Discord sez 
> Hero character cards should be targets, but we can add a null check I suppose.
but …
> Workaround SwitchCardsAction crashing for nontarget hero characters

- CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/TimeFreezeCardController.cs
Conveniently also makes the handling of Playing Dice with the Cosmos less special-cased.
Algorithm:
- Get asked before any other card; take full control of the process by never returning null.
- Ask every other card who they think should be the next turntaker (using reflection)
- If the answer we get out is the frozen turntaker, ask again as if they'd just taken their turn and the engine has moved on, then return that answer.
This means we can respect other turn-changer cards, without special-casing them, while still preventing the frozen turntaker taking a turn (unless another card says that the turntaker that should take a turn after the frozen turntaker is the frozen turntaker, in which case there's not really a great option and letting them have the turn is probably safest).
> Change Time Freeze to respect other turn-changers

- CauldronMods/Controller/Villains/Gray/CharacterCards/GrayTurnTakerController.cs
- CauldronMods/Controller/Villains/Menagerie/CharacterCards/MenagerieTurnTakerController.cs
- CauldronMods/Controller/Villains/PhaseVillain/CharacterCards/PhaseVillainTurnTakerController.cs
- CauldronMods/Controller/Villains/ScreaMachine/Cards/UpToElevenCardController.cs
- CauldronMods/Controller/Villains/TheRam/CharacterCards/PastTheRamCharacterCardController.cs
- CauldronMods/Controller/Villains/TheRam/CharacterCards/TheRamCharacterCardController.cs
- CauldronMods/Controller/Villains/TheRam/CharacterCards/TheRamTurnTakerController.cs
- CauldronMods/Controller/Villains/Tiamat/CardSubClasses/TiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CardSubClasses/TiamatSubCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/2199/FutureTiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/ElementalHydra/HydraWinterTiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/Regular/WinterTiamatCharacterCardController.cs
- CauldronMods/Controller/Villains/Tiamat/CharacterCards/TiamatTurnTakerController.cs
- CauldronMods/DeckLists/Villain/ScreaMachineDeckList.json
origamiswami found an interaction with Boss Rush and some Cauldron bosses where Ram, Gray, Menagerie, and Phase all put a card into play at the start of the game, but in their code, the card is played instead of put into play. This normally doesn't matter, but in Boss Rush, Take Down could be in play while the villain is setting up. This prevents those setup cards from getting played.
This fixes that issue
> Villain Start of Game Cards Should be Put into Play

- CauldronMods/Controller/Villains/Tiamat/CardSubClasses/SpellCardController.cs
- CauldronMods/Controller/Villains/Tiamat/Cards/ElementOfFireCardController.cs
- CauldronMods/Controller/Villains/Tiamat/Cards/ElementOfIceCardController.cs
- CauldronMods/Controller/Villains/Tiamat/Cards/ElementOfLightningCardController.cs
- Testing/Villains/TiamatFutureTests.cs
- Testing/Villains/TiamatTests.cs
the special string should include all the spell cards in the trash, not just the specified Element card. In this case, there are 4 spell cards in the trash, but the special string only considers Element of Ice cards.
In the constructor, CharacterCardController is still null, so the check previously never resolved correctly
> Future Tiamat and Spell card Special Strings

- CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/TimeFreezeCardController.cs
Sentinels 4.0.5 offers a method we can use for Time Freeze instead of reflection. At the moment the reflection version will crash in 4.0.5 because the method signature changed. This patch uses the new method so we'll continue working in 4.0.5.
> Undo time freeze workaround

- CauldronMods/DeckLists/Hero/DriftDeckList.json
Sentinels 4.0.5 fixes the engine bug that Drift's shift cards were made hero cards to avoid. This patch undoes the workaround.
> Make Drift's shift cards heroes again

- Testing/Villains/TheMistressOfFateTests.cs
A Mistress of Fate vs Dual Drift test doesn't actually specify which Drift cards to put into play at the start, and either the default has changed or something else has happened, because the test fails for me now. This patch fixes that.
> Fix TestHeroPreservation_DualDrift test

- Testing/Heroes/PyreTests.cs
Sentinels 4.0.5 fixed one engine bug around out-of-play cards causing damage, which broke some Pyre tests that were accounting for that bug. Explicitly add two tests for powers that previously the engine would have handled weirdly.
Also: I've replicated the bug with Cherenkov Drive triggering draws with official content (completionist guise, my love), so hopefully that'll get fixed in a later update.
> Pyre multi-damage test

- CauldronMods/Controller/Heroes/Gargoyle/CardSubClasses/GargoyleUtilityCardController.cs
- CauldronMods/Controller/Heroes/Gargoyle/Cards/LeechFieldCardController.cs
- Testing/Heroes/GargoyleTests.cs
In version 4.1, the SOTM engine now applies triggers created after a DealDamageAction is initiated but before it resolves to that DealDamageAction. One effect of this is that if Gargoyle has Leech Field in play, does damage to a target, and chooses to reduce his damage, the Leech Field increase is applied to the damage that was reduced.
This patch fixes that and adds a couple additional tests for interactions with Preemptive Payback raised with tosx on the Cauldron discord. It also cleans up the DDA flow a bit.
The workaround is to add an OnDealDamageStatusEffect that remembers the InstanceIdentifier of the DDA that triggered the Leech Field and does not act on that DDA.
> Fix Leech Field.

- CauldronMods/Controller/Villains/Dendron/CharacterCards/WindcolorDendronCharacterCardController.cs
- Testing/BaseTest.cs
- Testing/Villains/DendronVariantTests.cs
Closes #1617 
I've updated this under the literal assumption that cards under Windcolor Dendron are only not in play when Windcolor Dendron is on her front side. If this is not the case (pending tosx), this will need to be updated
> make tattoos under windcolor dendron not in play

- CauldronMods/Controller/Heroes/TangoOne/Cards/ChameleonArmorCardController.cs
- CauldronMods/Controller/Heroes/TangoOne/Cards/CriticalHitCardController.cs
- Testing/Heroes/TangoOneTests.cs
Closes #1596 
After thorough testing, I figured out that the infinite loop was happening during the Pretend phase. 
I added standalone triggers in Pretend to try to get the Damage Preview to not show the Error message, but it didn't work. If others have thoughts on how to get that to show as expected, I'm happy to see those
> Tango One - Shinobi Assassin + Chameleon Armor/Critical Hit

- CauldronMods/Controller/Villains/Anathema/CharacterCards/AcceleratedEvolutionAnathemaCharacterCardController.cs
- Testing/Villains/AnathemaVariantTests.cs
Closes #1643 
I'm not sure why they aren't auto destroying when indestructibility disappears if they have negative HP, but this is a workaround that will scan for any negative hp body parts on transition away from Anathema's turn
> Anathema Evolved - Body Parts Die at Negative HP

- CauldronMods/Controller/Heroes/LadyOfTheWood/CharacterCards/FutureLadyOfTheWoodCharacterCardController.cs
- Testing/Heroes/LadyOfTheWoodVariantTests.cs
The issue was caused by the game not being able to find Lady of the Wood's deck list after reloading the game, since it was looking for "LadyOfTheWoodDeckList" instead of "Cauldron.LadyOfTheWoodDeckList". The solution was to use TurnTaker.QualifiedIdentifier instead of TurnTaker.Identifier when handling the season cards after Lady is incapped, so after Lady's TurnTaker is replaced, the game can find the deck list in order to add the season cards to the new TurnTaker.
> Fix Lady of the Wood 2199 OblivAeon rewind bug

- CauldronMods/Controller/Heroes/Vanish/Cards/ForewarnedCardController.cs
Fixes infinite loop caused by Forewarned trying to make other heroes draw cards when she or they are Isolated. Now the player is prompted to choose the order for heroes to draw cards, and heroes that are not visible to Vanish are not included.
I'm not sure how to handle unit testing for this issue, since the fail state is an infinite loop.
> Fix for Forewarned Infinite Loop

- CauldronMods/Controller/Heroes/Terminus/Cards/GuiltyVerdictCardController.cs
- Testing/Heroes/TerminusTest.cs
Fixes issue where Guilty Verdict always triggered after other cards that trigger from the same damage, instead of giving a choice of which one should act first.
> 1636 terminus full moon express triggers before guilty verdict regardless of play order

- CauldronMods/Controller/Environments/SuperstormAkela/CardSubClasses/SuperstormAkelaCardController.cs
When the environment needs to refresh the UI when a card moves positions, it does this by flipping the card and then flipping it back. It chooses a random card to be the CardSource for this flip. It was coded to never choose the card that was calling `RefreshUI()` as the source, but I think the correct behavior should be to never choose the card that is being flipped as the CardSource. With the original behavior, it would occasionally choose the card that flipped, which would then be unable to flip back to the front side because it can't cause things while flipped. In unit tests, this would occasionally cause the test `TestRideTheCurrents_MoveTargetsAround` to fail.
I also added a debug line to help diagnose issues like this with Akela's cards in the future.
> Fix for Superstorm Akela Flip Bug

- CauldronMods/Controller/Heroes/TheKnight/CardSubClasses/TheKnightCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/Cards/PlateHelmCardController.cs
- CauldronMods/Controller/Heroes/TheKnight/Cards/PlateMailCardController.cs
- Testing/Heroes/TheKnightTests.cs
Closes #1682.
Moves the target maintenance triggers for the Knight's equipment targets to out-of-play triggers, added at the start of the game. Also tests.
> Fix Knight imbued vitality bug

- CauldronMods/Controller/Environments/SuperstormAkela/CardSubClasses/SuperstormAkelaCardController.cs
Typo in a recently merged pull request added a } where it shouldn't be
> Fix typo from recent Superstorm Akela fix

- CauldronMods/Controller/Heroes/Pyre/CardSubClasses/PyreUtilities.cs
- CauldronMods/Controller/Heroes/Pyre/CardSubClasses/PyreUtilityCardController.cs
- CauldronMods/Controller/Heroes/Pyre/CardSubClasses/PyreUtilityCharacterCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/AtmosphereScrubbersCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/AtomicPunchCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/CellularIrradiationCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/CherenkovDriveCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/ChromodynamicsCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/ContainmentBreachCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/FissionRegulatorCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/FracturedControlRodCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/GammaBurstCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/HalfLifeCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/IonTraceCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/NeutronForcefieldCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/ParticleColliderCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/RogueFissionCascadeCardController.cs
- CauldronMods/Controller/Heroes/Pyre/Cards/ThermonuclearCoreCardController.cs
- CauldronMods/Controller/Heroes/Pyre/CharacterCards/ExpeditionOblaskPyreCharacterCardController.cs
- CauldronMods/Controller/Heroes/Pyre/CharacterCards/PyreCharacterCardController.cs
- CauldronMods/Controller/Heroes/Pyre/CharacterCards/UnstablePyreCharacterCardController.cs
- CauldronMods/Controller/Heroes/Pyre/CharacterCards/WastelandRoninPyreCharacterCardController.cs
- CauldronMods/DeckLists/Hero/PyreDeckList.json
- Testing/Heroes/PyreTests.cs
Changes the way Pyre's markers work so that we only have one marker in the decklist and make new ones at runtime when we need them. This means we can irradiate more than 40 cards and also when you open pyre's cardlist you only see one copy of the marker card and it doesn't have to count to 40.
Also moves a bunch of code to extension methods, and makes the "is this an irradiated marker card?" check a bit more specific and consistent.
> Create irradiated markers at runtime. Move Pyre code to extension methods.

- Testing/Environments/FSCContinuanceWandererTests.cs
- Testing/Environments/NorthsparTests.cs
- Testing/Heroes/CricketVariantTests.cs
- Testing/Heroes/StarlightTests.cs
- Testing/Villains/TiamatHydraTests.cs
Tests involving Wager Master can fail due to a RNG game over if Losing to the Odds is in play, or if every starting condition is a Wageling. This pull request fixes all tests involving Wager Master by moving those cards to the trash before starting the game.
> Fix wager master tests

- CauldronMods/Controller/Villains/Celadroch/CharacterCards/CeladrochCharacterCardController.cs
Currently, the if-statements do not short-circuit and so the rng < 20 always evaluates. Because of this, the message is 95% of the time the last message
1-19: Forsaken Crusader says 'I serve'
20: Celadroch says 'Your service has not ended...'
With the update, it's now
1-5: Celadroch says 'Your service has not ended...'
6-10: Celadroch says 'Arise'
11-15: Forsaken Crusader says 'When can I slumber...'
16-20: Forsaken Crusader says 'I serve.'
> Fix Celadroch reviving Forsaken Crusader easter egg message

- CauldronMods/Controller/Environments/OblaskCrater/Cards/MetalScavengerCardController.cs
- Testing/Environments/OblaskCraterTests.cs
Fixes Metal Scavenger so it doesn't move cards from trashes in the other battle zone
> Metal Scavenger OblivAeon fix

- CauldronMods/Controller/Heroes/DocHavoc/CharacterCards/FirstResponseDocHavocCharacterCardController.cs
- Testing/Heroes/DocHavocPromoTests.cs
> Fix for First Response Doc Havoc Incap 3 Allowing Destruction of Non-Target Environment Cards

- CauldronMods/Controller/Heroes/Terminus/Cards/FlashBeforeYourEyesCardController.cs
- Testing/Heroes/TerminusTest.cs
I think the issue described in this bug report was actually caused by visibility issues in OblivAeon mode. Flash Before Your Eyes would determine if Terminus can see a trash based on whether Terminus can see that trash's TurnTaker. For the Scion and Aeon Men trashes, this meant that Terminus could see those trashes if and only if she was in the same BZ as OblivAeon. I confirmed that the bug still exists and fixed the card so that it checks visibility of the trash itself.
> 1492 flash before your eyes prevents different oa decks in later rounds

- CauldronMods/Controller/Heroes/Cricket/CharacterCards/WastelandRoninCricketCharacterCardController.cs
- Testing/Heroes/CricketVariantTests.cs
The issue here was that if you reload the game after Wasteland Ronin Cricket is incapped and replaced with a new hero, her second incap ability does not work. It will create the status effect, but not allow you to use the power twice.
The cause of the issue was that in AddSideTriggers(), Cricket is checking if base.CharacterCard is flipped before adding the trigger for incap 2. Since Cricket was replaced with a new hero, base.CharacterCard now refers to that hero's character card, which is not flipped, so when the game is reloaded it never adds the trigger to make the incap ability work. It works before reloading because in that case, the trigger is added when Cricket flips.
The fix is to check if base.Card is flipped instead of base.CharacterCard.
> 1579 wasteland ronin cricket incap not working correctly

- CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftSubCharacterCardController.cs
- Testing/Heroes/DriftTests.cs
From BartKF:
> Choosing Drift as the Representative of Earth makes it impossible to load saves. Apparently something is expecting The Celestial Tribunal's deck to have a card with the identifier TheCelestialTribunal, and when it doesn't, the save refuses to load.
This was a result in bad logic for the loading of the Shift Tracks. Fixing this logic resolved the issue.
> fix logic for shift tracks for when drift is representative of earth

- CauldronMods/Controller/Environments/StSimeonsCatacombs/CardSubClasses/StSimeonsGhostCardController.cs
- CauldronMods/Controller/Environments/StSimeonsCatacombs/CardSubClasses/StSimeonsRoomCardController.cs
- CauldronMods/Controller/Villains/Menagerie/Cards/SecuritySphereCardController.cs
- Testing/Environments/StSimeonsCatacombsTests.cs
Changes to FindCardsWhere caused an infinite loop in St Simeon's Catacombs, crashing the game. This pull request fixes the issue and adds a unit test.
> St Simeons 4.1.1 crash fix
